CodeSystem: CS_NCLPPOL
Id: NCLPPOL
Title: "NCLPPOL Code System"
Description: "Národní číselník laboratorních položek"
* ^language = #cs
// * ^extension.url = "http://hl7.org/fhir/StructureDefinition/cqf-knowledgeRepresentationLevel"
// * ^extension.valueCode = #executable
* ^url = "https://ncez.mzcr.cz/nclp/CodeSystem/nclppol"
* ^version = "02.97.01"
* ^status = #active
* ^experimental = false
* ^date = "2026-06-02T14:38:49Z"
* ^publisher = "MZČR"
* ^jurisdiction = urn:iso:std:iso:3166#CZ "Czechia"
// * ^effectivePeriod.start = "2026-06-02T00:00:00Z"
* ^caseSensitive = false
* ^content = #fragment

* #00001 "Dikarboxyporfyriny celkové (Porfyriny celkové(stolice); látkový podíl [1] *)"
* #00002 "Dikarboxyporfyriny celkové (Porfyriny celkové(stolice); látkový podíl [1] Chromatografie-HPLC)"
* #00003 "Dikarboxyporfyriny celkové (Porfyriny celkové(U); látkový podíl [1] *)"
* #00004 "Dikarboxyporfyriny celkové (Porfyriny celkové(U); látkový podíl [1] Chromatografie-HPLC)"
* #00005 "2-hydroxybutyrát (P; látková konc. [mmol/l] *)"
* #00006 "2-hydroxybutyrát (P; látková konc. [mmol/l] Izotachoforéza)"
* #00007 "2-hydroxybutyrát (S; látková konc. [mmol/l] *)"
* #00008 "2-hydroxybutyrát (S; látková konc. [mmol/l] Izotachoforéza)"
* #00009 "3-hydroxybutyrát (P; látková konc. [mmol/l] *)"
* #00010 "3-hydroxybutyrát (P; látková konc. [mmol/l] Izotachoforéza)"
* #00011 "3-hydroxybutyrát (S; látková konc. [mmol/l] *)"
* #00012 "3-hydroxybutyrát (S; látková konc. [mmol/l] Izotachoforéza)"
* #00013 "4-aminobenzoát (dU; látkový tok [mmol/d] *)"
* #00014 "4-aminobenzoát (dU; látkový tok [mmol/d] Absorpční spektrofotometrie)"
* #00015 "4-aminobenzoát (S; látková konc. [µmol/l] *)"
* #00016 "4-aminobenzoát (S; látková konc. [µmol/l] Absorpční spektrofotometrie)"
* #00017 "4-aminobenzoát (U; látková konc. [mmol/l] *)"
* #00018 "4-aminobenzoát (U; látková konc. [mmol/l] Absorpční spektrofotometrie)"
* #00019 "Zevní sekrece pankreatu (Pt; rel. látkové množ. [1] *)"
* #00020 "4-aminohippurát (S; hmot. konc. [mg/l] *)"
* #00021 "4-aminohippurát (S; hmot. konc. [mg/l] Absorpční spektrofotom. registr.)"
* #00022 "4-aminohippurát (U; hmot. konc. [mg/l] *)"
* #00023 "4-aminohippurát (U; hmot. konc. [mg/l] Absorpční spektrofotom. registr.)"
* #00024 "Pentakarboxyporfyrin (Porfyriny celkové(stolice); látkový podíl [1] *)"
* #00025 "Pentakarboxyporfyrin (Porfyriny celkové(stolice); látkový podíl [1] Chromatografie-HPLC)"
* #00026 "Pentakarboxyporfyrin (Porfyriny celkové(U); látkový podíl [1] *)"
* #00027 "Pentakarboxyporfyrin (Porfyriny celkové(U); látkový podíl [1] Chromatografie-HPLC)"
* #00028 "5-hydroxyindolacetát (Likvor; látková konc. [nmol/l] *)"
* #00029 "5-hydroxyindolacetát (Likvor; látková konc. [nmol/l] Chromatografie-HPLC)"
* #00030 "5-hydroxyindolacetát (dU; látkový tok [µmol/d] *)"
* #00031 "5-hydroxyindolacetát (dU; látkový tok [µmol/d] Chromatografie-HPLC)"
* #00032 "5-hydroxyindolacetát (P; látková konc. [nmol/l] *)"
* #00033 "5-hydroxyindolacetát (P; látková konc. [nmol/l] Chromatografie-HPLC)"
* #00034 "5-hydroxyindolacetát (S; látková konc. [nmol/l] *)"
* #00035 "5-hydroxyindolacetát (S; látková konc. [nmol/l] Chromatografie-HPLC)"
* #00036 "5-hydroxyindolacetát (U; látková konc. [µmol/l] *)"
* #00037 "5-hydroxyindolacetát (U; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00038 "Hexakarboxyporfyrin (Porfyriny celkové(stolice); látkový podíl [1] *)"
* #00039 "Hexakarboxyporfyrin (Porfyriny celkové(stolice); látkový podíl [1] Chromatografie-HPLC)"
* #00040 "Hexakarboxyporfyrin (Porfyriny celkové(U); látkový podíl [1] *)"
* #00041 "Hexakarboxyporfyrin (Porfyriny celkové(U); látkový podíl [1] Chromatografie-HPLC)"
* #00042 "Heptakarboxyporfyrin (Porfyriny celkové(stolice); látkový podíl [1] *)"
* #00043 "Heptakarboxyporfyrin (Porfyriny celkové(stolice); látkový podíl [1] Chromatografie-HPLC)"
* #00044 "Heptakarboxyporfyrin (Porfyriny celkové(U); látkový podíl [1] *)"
* #00045 "Heptakarboxyporfyrin (Porfyriny celkové(U); látkový podíl [1] Chromatografie-HPLC)"
* #00046 "Alfa-1-antitrypsin (P; hmot. konc. [g/l] *)"
* #00047 "Alfa-1-antitrypsin (P; hmot. konc. [g/l] ELISA)"
* #00048 "Alfa-1-antitrypsin (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00049 "Alfa-1-antitrypsin (P; hmot. konc. [g/l] Nefelometrie)"
* #00050 "Alfa-1-antitrypsin (P; hmot. konc. [g/l] Radiální imunodifuze)"
* #00051 "Alfa-1-antitrypsin (S; hmot. konc. [g/l] *)"
* #00052 "Alfa-1-antitrypsin (S; hmot. konc. [g/l] ELISA)"
* #00053 "Alfa-1-antitrypsin (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00054 "Alfa-1-antitrypsin (S; hmot. konc. [g/l] Nefelometrie)"
* #00055 "Alfa-1-antitrypsin (S; hmot. konc. [g/l] Radiální imunodifuze)"
* #00056 "Alfa-1-globulin (Likvor; hmot. konc. [g/l] *)"
* #00057 "Alfa-1-globulin (Likvor; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00058 "Alfa-1-globulin (Likvor; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00059 "Alfa-1-globulin (P; hmot. konc. [g/l] *)"
* #00060 "Alfa-1-globulin (P; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00061 "Alfa-1-globulin (P; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00062 "Alfa-1-globulin (Pleurální tekutina; hmot. konc. [g/l] *)"
* #00063 "Alfa-1-globulin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00064 "Alfa-1-globulin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00065 "Alfa-1-globulin (Peritoneální tekutina; hmot. konc. [g/l] *)"
* #00066 "Alfa-1-globulin (Peritoneální tekutina; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00067 "Alfa-1-globulin (Peritoneální tekutina; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00068 "Alfa-1-globulin (Protein(Csf.); hmot. podíl [1] *)"
* #00069 "Alfa-1-globulin (Protein(Csf.); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00070 "Alfa-1-globulin (Protein(Csf.); hmot. podíl [1] Elektroforéza-agaróza)"
* #00071 "Alfa-1-globulin (Protein(P); hmot. podíl [1] *)"
* #00072 "Alfa-1-globulin (Protein(P); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00073 "Alfa-1-globulin (Protein(P); hmot. podíl [1] Elektroforéza-agaróza)"
* #00074 "Alfa-1-globulin (Protein(pleurální tekutina); hmot. podíl [1] *)"
* #00075 "Alfa-1-globulin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00076 "Alfa-1-globulin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza-agaróza)"
* #00077 "Alfa-1-globulin (Protein(periton. tekutina); hmot. podíl [1] *)"
* #00078 "Alfa-1-globulin (Protein(periton. tekutina); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00079 "Alfa-1-globulin (Protein(periton. tekutina); hmot. podíl [1] Elektroforéza-agaróza)"
* #00080 "Alfa-1-globulin (Protein(S); hmot. podíl [1] *)"
* #00081 "Alfa-1-globulin (Protein(S); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00082 "Alfa-1-globulin (Protein(S); hmot. podíl [1] Elektroforéza-agaróza)"
* #00083 "Alfa-1-globulin (Protein(U); hmot. podíl [1] *)"
* #00084 "Alfa-1-globulin (Protein(U); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00085 "Alfa-1-globulin (Protein(U); hmot. podíl [1] Elektroforéza-agaróza)"
* #00086 "Alfa-1-globulin (S; hmot. konc. [g/l] *)"
* #00087 "Alfa-1-globulin (S; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00088 "Alfa-1-globulin (S; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00089 "Alfa-1-globulin (U; hmot. konc. [g/l] *)"
* #00090 "Alfa-1-globulin (U; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00091 "Alfa-1-globulin (U; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00092 "Alfa-2-globulin (Likvor; hmot. konc. [g/l] *)"
* #00093 "Alfa-2-globulin (Likvor; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00094 "Alfa-2-globulin (Likvor; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00095 "Alfa-2-globulin (P; hmot. konc. [g/l] *)"
* #00096 "Alfa-2-globulin (P; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00097 "Alfa-2-globulin (P; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00098 "Alfa-2-globulin (Pleurální tekutina; hmot. konc. [g/l] *)"
* #00099 "Alfa-2-globulin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00100 "Alfa-2-globulin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00101 "Alfa-2-globulin (Peritoneální tekutina; hmot. konc. [g/l] *)"
* #00102 "Alfa-2-globulin (Peritoneální tekutina; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00103 "Alfa-2-globulin (Peritoneální tekutina; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00104 "Alfa-2-globulin (Protein(Csf.); hmot. podíl [1] *)"
* #00105 "Alfa-2-globulin (Protein(Csf.); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00106 "Alfa-2-globulin (Protein(Csf.); hmot. podíl [1] Elektroforéza-agaróza)"
* #00107 "Alfa-2-globulin (Protein(P); hmot. podíl [1] *)"
* #00108 "Alfa-2-globulin (Protein(P); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00109 "Alfa-2-globulin (Protein(P); hmot. podíl [1] Elektroforéza-agaróza)"
* #00110 "Alfa-2-globulin (Protein(pleurální tekutina); hmot. podíl [1] *)"
* #00111 "Alfa-2-globulin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00112 "Alfa-2-globulin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza-agaróza)"
* #00113 "Alfa-2-globulin (Protein(periton. tekutina); hmot. podíl [1] *)"
* #00114 "Alfa-2-globulin (Protein(periton. tekutina); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00115 "Alfa-2-globulin (Protein(periton. tekutina); hmot. podíl [1] Elektroforéza-agaróza)"
* #00116 "Alfa-2-globulin (Protein(S); hmot. podíl [1] *)"
* #00117 "Alfa-2-globulin (Protein(S); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00118 "Alfa-2-globulin (Protein(S); hmot. podíl [1] Elektroforéza-agaróza)"
* #00119 "Alfa-2-globulin (Protein(U); hmot. podíl [1] *)"
* #00120 "Alfa-2-globulin (Protein(U); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00121 "Alfa-2-globulin (Protein(U); hmot. podíl [1] Elektroforéza-agaróza)"
* #00122 "Alfa-2-globulin (S; hmot. konc. [g/l] *)"
* #00123 "Alfa-2-globulin (S; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00124 "Alfa-2-globulin (S; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00125 "Alfa-2-globulin (U; hmot. konc. [g/l] *)"
* #00126 "Alfa-2-globulin (U; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00127 "Alfa-2-globulin (U; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00128 "Alfa-2-makroglobulin (P; hmot. konc. [g/l] *)"
* #00129 "Alfa-2-makroglobulin (P; hmot. konc. [g/l] ELISA)"
* #00130 "Alfa-2-makroglobulin (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00131 "Alfa-2-makroglobulin (P; hmot. konc. [g/l] Nefelometrie)"
* #00132 "Alfa-2-makroglobulin (P; hmot. konc. [g/l] Radiální imunodifuze)"
* #00133 "Alfa-2-makroglobulin (S; hmot. konc. [g/l] *)"
* #00134 "Alfa-2-makroglobulin (S; hmot. konc. [g/l] ELISA)"
* #00135 "Alfa-2-makroglobulin (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00136 "Alfa-2-makroglobulin (S; hmot. konc. [g/l] Nefelometrie)"
* #00137 "Alfa-2-makroglobulin (S; hmot. konc. [g/l] Radiální imunodifuze)"
* #00138 "2-aminoadipát (dU; látkový tok [µmol/d] *)"
* #00139 "2-aminoadipát (dU; látkový tok [µmol/d] Chromatografie-IEC)"
* #00140 "2-aminoadipát (P; látková konc. [µmol/l] *)"
* #00141 "2-aminoadipát (P; látková konc. [µmol/l] Chromatografie-IEC)"
* #00142 "2-aminoadipát (S; látková konc. [µmol/l] *)"
* #00143 "2-aminoadipát (S; látková konc. [µmol/l] Chromatografie-IEC)"
* #00144 "2-aminoadipát (U; látková konc. [µmol/l] *)"
* #00145 "2-aminoadipát (U; látková konc. [µmol/l] Chromatografie-IEC)"
* #00146 "Anti-Adenovirus (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00147 "Anti-Adenovirus (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00148 "Anti-Adenovirus (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00149 "Anti-Adenovirus (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00150 "Anti-Borrelia burgdorferi IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00151 "Anti-Borrelia burgdorferi IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00152 "Anti-Borrelia burgdorferi IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00153 "Anti-Borrelia burgdorferi IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00154 "Anti-Borrelia burgdorferi IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00155 "Anti-Borrelia burgdorferi IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00156 "Anti-Borrelia burgdorferi IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00157 "Anti-Borrelia burgdorferi IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00158 "Anti-Borrelia burgdorferi IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00159 "Anti-Borrelia burgdorferi IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00160 "Anti-Borrelia burgdorferi IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00161 "Anti-Borrelia burgdorferi IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00162 "Anti-Bordetella parapertussis (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00163 "Anti-Bordetella parapertussis (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00164 "Anti-Bordetella parapertussis (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00165 "Anti-Bordetella parapertussis (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00166 "Anti-Bordetella pertussis (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00167 "Anti-Bordetella pertussis (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00168 "Anti-Bordetella pertussis (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00169 "Anti-Bordetella pertussis (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00170 "Anti-Brucella abortus (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00171 "Anti-Brucella abortus (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00172 "Anti-Brucella abortus (titr) (P; arb. konc. (titr) [arb.j.] Aglut. blok. protilátek)"
* #00173 "Anti-Brucella abortus (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00174 "Anti-Brucella abortus (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00175 "Anti-Brucella abortus (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00176 "Anti-Brucella abortus (titr) (S; arb. konc. (titr) [arb.j.] Aglut. blok. protilátek)"
* #00177 "Anti-Brucella abortus (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00178 "Acetoacetát (P; látková konc. [mmol/l] *)"
* #00179 "Acetoacetát (P; látková konc. [mmol/l] Absorpční spektrofotometrie)"
* #00180 "Acetoacetát (P; látková konc. [mmol/l] Elektroforéza-HPCE)"
* #00181 "Acetoacetát (P; látková konc. [mmol/l] Izotachoforéza)"
* #00182 "Acetoacetát (S; látková konc. [mmol/l] *)"
* #00183 "Acetoacetát (S; látková konc. [mmol/l] Absorpční spektrofotometrie)"
* #00184 "Acetoacetát (S; látková konc. [mmol/l] Elektroforéza-HPCE)"
* #00185 "Acetoacetát (S; látková konc. [mmol/l] Izotachoforéza)"
* #00186 "Anti-Campylobacter jejuni IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00187 "Anti-Campylobacter jejuni IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00188 "Anti-Campylobacter jejuni IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00189 "Anti-Campylobacter jejuni IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00190 "Acetát (P; látková konc. [mmol/l] *)"
* #00191 "Acetát (P; látková konc. [mmol/l] Izotachoforéza)"
* #00192 "Acetát (S; látková konc. [mmol/l] *)"
* #00193 "Acetát (S; látková konc. [mmol/l] Izotachoforéza)"
* #00194 "Anti-Chlamydia psittaci (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00195 "Anti-Chlamydia psittaci (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00196 "Anti-Chlamydia psittaci (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00197 "Anti-Chlamydia psittaci (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00198 "Anti-Chlamydia trachomatis IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00199 "Anti-Chlamydia trachomatis IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00200 "Anti-Chlamydia trachomatis IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00201 "Anti-Chlamydia trachomatis IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00202 "Anti-Chlamydia trachomatis IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00203 "Anti-Chlamydia trachomatis IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00204 "Anti-CMV IgA (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00205 "Anti-CMV IgA (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00206 "Anti-CMV IgA (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00207 "Anti-CMV IgA (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00208 "Anti-CMV IgA (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00209 "Anti-CMV IgA (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00210 "Anti-CMV IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00211 "Anti-CMV IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00212 "Anti-CMV IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00213 "Anti-CMV IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00214 "Anti-CMV IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00215 "Anti-CMV IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00216 "Anti-CMV IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00217 "Anti-CMV IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00218 "Anti-CMV IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00219 "Anti-CMV IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00220 "Anti-CMV IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00221 "Anti-CMV IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00222 "Anti-CMV (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00223 "Anti-CMV (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00224 "Anti-CMV (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00225 "Anti-CMV (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00226 "Anti-Coxiella burnetii (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00227 "Anti-Coxiella burnetii (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00228 "Anti-Coxiella burnetii (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00229 "Anti-Coxiella burnetii (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00230 "Anti-Coxsackie B1 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00231 "Anti-Coxsackie B1 (titr) (P; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00232 "Anti-Coxsackie B1 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00233 "Anti-Coxsackie B1 (titr) (S; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00234 "Anti-Coxsackie B2 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00235 "Anti-Coxsackie B2 (titr) (P; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00236 "Anti-Coxsackie B2 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00237 "Anti-Coxsackie B2 (titr) (S; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00238 "Anti-Coxsackie B3 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00239 "Anti-Coxsackie B3 (titr) (P; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00240 "Anti-Coxsackie B3 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00241 "Anti-Coxsackie B3 (titr) (S; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00242 "Anti-Coxsackie B4 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00243 "Anti-Coxsackie B4 (titr) (P; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00244 "Anti-Coxsackie B4 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00245 "Anti-Coxsackie B4 (titr) (S; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00246 "Anti-Coxsackie B5 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00247 "Anti-Coxsackie B5 (titr) (P; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00248 "Anti-Coxsackie B5 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00249 "Anti-Coxsackie B5 (titr) (S; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00250 "Anti-Coxsackie B6 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00251 "Anti-Coxsackie B6 (titr) (P; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00252 "Anti-Coxsackie B6 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00253 "Anti-Coxsackie B6 (titr) (S; arb. konc. (titr) [arb.j.] Test virus-neutralizační)"
* #00254 "ACP (P; konc. katal. akt. [µkat/l] *)"
* #00255 "ACP (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00256 "ACP (S; konc. katal. akt. [µkat/l] *)"
* #00257 "ACP (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00258 "ACP prostatická (P; konc. katal. akt. [µkat/l] *)"
* #00259 "ACP prostatická (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00260 "ACP prostatická (S; konc. katal. akt. [µkat/l] *)"
* #00261 "ACP prostatická (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00262 "N4-acetyl-sulfadiazin (Konkrement (močový); objemový podíl [1] Spektroskopie-IR)"
* #00263 "N4-acetyl-sulfadiazin (Konkrement (močový); objemový podíl [1] Mikroskopie)"
* #00264 "N4-acetylsulfamethoxazol (Konkrement (močový); objemový podíl [1] Spektroskopie-IR)"
* #00265 "N4-acetylsulfamethoxazol (Konkrement (močový); objemový podíl [1] Mikroskopie)"
* #00266 "Antigen Adenovirus (Stolice; arb. konc. [arb.j.] *)"
* #00267 "Antigen Adenovirus (Stolice; arb. konc. [arb.j.] ELISA)"
* #00268 "Antigen Adenovirus (Stolice; arb. konc. [arb.j.] Aglutinace (latex))"
* #00269 "Antigen Adenovirus (Sekret; arb. konc. [arb.j.] *)"
* #00270 "Antigen Adenovirus (Sekret; arb. konc. [arb.j.] IA)"
* #00271 "Anti-ds-DNA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00272 "Anti-ds-DNA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00273 "Anti-ds-DNA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00274 "Anti-ds-DNA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00275 "Anti-ds-DNA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00276 "Anti-ds-DNA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00277 "Anti-ss-DNA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00278 "Anti-ss-DNA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00279 "Anti-ss-DNA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00280 "Anti-ss-DNA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00281 "Anti-ss-DNA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00282 "Anti-ss-DNA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00283 "Adrenalin (dU; látkový tok [nmol/d] *)"
* #00284 "Adrenalin (dU; látkový tok [nmol/d] Chromatografie-HPLC)"
* #00285 "Adrenalin (P; látková konc. [nmol/l] *)"
* #00286 "Adrenalin (P; látková konc. [nmol/l] Chromatografie-HPLC)"
* #00287 "Adrenalin (S; látková konc. [nmol/l] *)"
* #00288 "Adrenalin (S; látková konc. [nmol/l] Chromatografie-HPLC)"
* #00289 "Adrenalin (U; látková konc. [nmol/l] *)"
* #00290 "Adrenalin (U; látková konc. [nmol/l] Chromatografie-HPLC)"
* #00291 "Anti-EBV/EA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00292 "Anti-EBV/EA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00293 "Anti-EBV/EA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00294 "Anti-EBV/EA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00295 "Anti-EBV/EA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00296 "Anti-EBV/EA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00297 "Anti-EBV/EA IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00298 "Anti-EBV/EA IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00299 "Anti-EBV/EA IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00300 "Anti-EBV/EA IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00301 "Anti-EBV/EA IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00302 "Anti-EBV/EA IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00303 "Anti-EBV/EBNA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00304 "Anti-EBV/EBNA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00305 "Anti-EBV/EBNA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00306 "Anti-EBV/EBNA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00307 "Anti-EBV/EBNA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00308 "Anti-EBV/EBNA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00309 "Anti-EBV/EBNA IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00310 "Anti-EBV/EBNA IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00311 "Anti-EBV/EBNA IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00312 "Anti-EBV/EBNA IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00313 "Anti-EBV/EBNA IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00314 "Anti-EBV/EBNA IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00315 "Anti-EBV/VCA IgA (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00316 "Anti-EBV/VCA IgA (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00317 "Anti-EBV/VCA IgA (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00318 "Anti-EBV/VCA IgA (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00319 "Anti-EBV/VCA IgA (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00320 "Anti-EBV/VCA IgA (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00321 "Anti-EBV/VCA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00322 "Anti-EBV/VCA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00323 "Anti-EBV/VCA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00324 "Anti-EBV/VCA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00325 "Anti-EBV/VCA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00326 "Anti-EBV/VCA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00327 "Anti-EBV/VCA IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00328 "Anti-EBV/VCA IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00329 "Anti-EBV/VCA IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00330 "Anti-EBV/VCA IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00331 "Anti-EBV/VCA IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00332 "Anti-EBV/VCA IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00333 "Anti-Escherichia coli (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00334 "Anti-Escherichia coli (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00335 "Anti-Escherichia coli (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00336 "Anti-Escherichia coli (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00337 "Anti-Escherichia coli (titr) (U; arb. konc. (titr) [arb.j.] *)"
* #00338 "Anti-Escherichia coli (titr) (U; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00339 "Alfa-1-fetoprotein (Amniová tekutina; arb. látková konc. [MU/l] *)"
* #00340 "Alfa-1-fetoprotein (Amniová tekutina; arb. látková konc. [MU/l] RIA)"
* #00341 "Alfa-1-fetoprotein (P; arb. látková konc. [kU/l] *)"
* #00342 "Alfa-1-fetoprotein (P; arb. látková konc. [kU/l] IRMA)"
* #00343 "Alfa-1-fetoprotein (S; arb. látková konc. [kU/l] *)"
* #00344 "Alfa-1-fetoprotein (S; arb. látková konc. [kU/l] ELISA)"
* #00345 "Alfa-1-fetoprotein (S; arb. látková konc. [kU/l] IRMA)"
* #00346 "Anti-Francisella tularensis (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00347 "Anti-Francisella tularensis (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00348 "Anti-Francisella tularensis (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00349 "Anti-Francisella tularensis (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00350 "Anti-gliadin IgA index (S; rel. látkový poměr [1] *)"
* #00351 "Anti-gliadin IgA index (S; rel. látkový poměr [1] ELISA)"
* #00352 "Anti-gliadin IgE (S; rel. látkový poměr [1] *)"
* #00353 "Anti-gliadin IgE (S; rel. látkový poměr [1] ELISA)"
* #00354 "Anti-gliadin IgG - index (S; rel. látkový poměr [1] *)"
* #00355 "Anti-gliadin IgG - index (S; rel. látkový poměr [1] ELISA)"
* #00356 "Albumino-globulinový kvocient (P; hmot. poměr [1] *)"
* #00357 "Albumino-globulinový kvocient (P; hmot. poměr [1] Elektroforéza-acetylcelulóza)"
* #00358 "Albumino-globulinový kvocient (P; hmot. poměr [1] Elektroforéza-agaróza)"
* #00359 "Albumino-globulinový kvocient (S; hmot. poměr [1] *)"
* #00360 "Albumino-globulinový kvocient (S; hmot. poměr [1] Elektroforéza-acetylcelulóza)"
* #00361 "Albumino-globulinový kvocient (S; hmot. poměr [1] Elektroforéza-agaróza)"
* #00362 "Anti-HAV celkové (P; arb. konc. [arb.j.] *)"
* #00363 "Anti-HAV celkové (P; arb. konc. [arb.j.] ELISA)"
* #00364 "Anti-HAV celkové (S; arb. konc. [arb.j.] *)"
* #00365 "Anti-HAV celkové (S; arb. konc. [arb.j.] ELISA)"
* #00366 "Anti-HAV IgM (P; arb. konc. [arb.j.] *)"
* #00367 "Anti-HAV IgM (P; arb. konc. [arb.j.] ELISA)"
* #00368 "Anti-HAV IgM (S; arb. konc. [arb.j.] *)"
* #00369 "Anti-HAV IgM (S; arb. konc. [arb.j.] ELISA)"
* #00370 "Anti-HBcAg (P; arb. konc. [arb.j.] *)"
* #00371 "Anti-HBcAg (P; arb. konc. [arb.j.] ELISA)"
* #00372 "Anti-HBcAg (S; arb. konc. [arb.j.] *)"
* #00373 "Anti-HBcAg (S; arb. konc. [arb.j.] ELISA)"
* #00374 "Anti-HBeAg (P; arb. konc. [arb.j.] *)"
* #00375 "Anti-HBeAg (P; arb. konc. [arb.j.] ELISA)"
* #00376 "Anti-HBeAg (S; arb. konc. [arb.j.] *)"
* #00377 "Anti-HBeAg (S; arb. konc. [arb.j.] ELISA)"
* #00378 "Anti-HBsAg (P; arb. konc. [arb.j.] *)"
* #00379 "Anti-HBsAg (P; arb. konc. [arb.j.] ELISA)"
* #00380 "Anti-HBsAg (S; arb. konc. [arb.j.] *)"
* #00381 "Anti-HBsAg (S; arb. konc. [arb.j.] ELISA)"
* #00382 "Anti-HCV celkové (P; arb. konc. [arb.j.] *)"
* #00383 "Anti-HCV celkové (P; arb. konc. [arb.j.] ELISA)"
* #00384 "Anti-HCV celkové (S; arb. konc. [arb.j.] *)"
* #00385 "Anti-HCV celkové (S; arb. konc. [arb.j.] ELISA)"
* #00386 "Anti-Helicobacter pylori IgA (P; arb. látková konc. [U/l] *)"
* #00387 "Anti-Helicobacter pylori IgA (P; arb. látková konc. [U/l] ELISA)"
* #00388 "Anti-Helicobacter pylori IgA (S; arb. látková konc. [U/l] *)"
* #00389 "Anti-Helicobacter pylori IgA (S; arb. látková konc. [U/l] ELISA)"
* #00390 "Anti-Helicobacter pylori IgG (P; arb. látková konc. [U/l] *)"
* #00391 "Anti-Helicobacter pylori IgG (P; arb. látková konc. [U/l] ELISA)"
* #00392 "Anti-Helicobacter pylori IgG (S; arb. látková konc. [U/l] *)"
* #00393 "Anti-Helicobacter pylori IgG (S; arb. látková konc. [U/l] ELISA)"
* #00394 "Anti-Helicobacter pylori IgM (P; arb. látková konc. [U/l] *)"
* #00395 "Anti-Helicobacter pylori IgM (P; arb. látková konc. [U/l] ELISA)"
* #00396 "Anti-Helicobacter pylori IgM (S; arb. látková konc. [U/l] *)"
* #00397 "Anti-Helicobacter pylori IgM (S; arb. látková konc. [U/l] ELISA)"
* #00398 "Anti-HSV IgA (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00399 "Anti-HSV IgA (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00400 "Anti-HSV IgA (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00401 "Anti-HSV IgA (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00402 "Anti-HSV IgA (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00403 "Anti-HSV IgA (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00404 "Anti-HSV IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00405 "Anti-HSV IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00406 "Anti-HSV IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00407 "Anti-HSV IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00408 "Anti-HSV IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00409 "Anti-HSV IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00410 "Anti-HSV IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00411 "Anti-HSV IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00412 "Anti-HSV IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00413 "Anti-HSV IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00414 "Anti-HSV IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00415 "Anti-HSV IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00416 "Anti-HSV (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00417 "Anti-HSV (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00418 "Anti-HSV (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00419 "Anti-HSV (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00420 "Anti-imunoglobuliny (P; arb. látková konc. [kU/l] *)"
* #00421 "Anti-imunoglobuliny (P; arb. látková konc. [kU/l] Nefelometrie)"
* #00422 "Anti-imunoglobuliny (S; arb. látková konc. [kU/l] *)"
* #00423 "Anti-imunoglobuliny (S; arb. látková konc. [kU/l] Nefelometrie)"
* #00424 "Anti-imunoglobuliny (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00425 "Anti-imunoglobuliny (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace (latex))"
* #00426 "Anti-imunoglobuliny (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00427 "Anti-imunoglobuliny (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace (latex))"
* #00428 "Anti-Influenza A1 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00429 "Anti-Influenza A1 (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00430 "Anti-Influenza A1 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00431 "Anti-Influenza A1 (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00432 "Anti-Influenza A2 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00433 "Anti-Influenza A2 (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00434 "Anti-Influenza A2 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00435 "Anti-Influenza A2 (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00436 "Anti-Influenza B (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00437 "Anti-Influenza B (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00438 "Anti-Influenza B (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00439 "Anti-Influenza B (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00440 "VDRL/RRR (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00441 "VDRL/RRR (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00442 "VDRL/RRR (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00443 "VDRL/RRR (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00444 "Al (dU; látkový tok [µmol/d] *)"
* #00445 "Al (dU; látkový tok [µmol/d] AAS)"
* #00446 "Al (Vlas; látkový obsah [µmol/kg] *)"
* #00447 "Al (Vlas; látkový obsah [µmol/kg] AAS)"
* #00448 "Al (Játra(biopsie); látkový obsah [mmol/kg] *)"
* #00449 "Al (Játra(biopsie); látkový obsah [mmol/kg] AAS)"
* #00450 "Al (S; látková konc. [µmol/l] *)"
* #00451 "Al (S; látková konc. [µmol/l] AAS)"
* #00452 "Al (U; látková konc. [µmol/l] *)"
* #00453 "Al (U; látková konc. [µmol/l] AAS)"
* #00454 "Alanin (Likvor; látková konc. [µmol/l] *)"
* #00455 "Alanin (Likvor; látková konc. [µmol/l] Chromatografie-IEC)"
* #00456 "Alanin (dU; látkový tok [µmol/d] *)"
* #00457 "Alanin (dU; látkový tok [µmol/d] Chromatografie-HPLC)"
* #00458 "Alanin (dU; látkový tok [µmol/d] Chromatografie-IEC)"
* #00459 "Alanin (dU; látkový tok [µmol/d] Chromatografie-TLC)"
* #00460 "Alanin (P; látková konc. [µmol/l] *)"
* #00461 "Alanin (P; látková konc. [µmol/l] Chromatografie-IEC)"
* #00462 "Alanin (S; látková konc. [µmol/l] *)"
* #00463 "Alanin (S; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00464 "Alanin (S; látková konc. [µmol/l] Chromatografie-IEC)"
* #00465 "Alanin (S; látková konc. [µmol/l] Chromatografie-TLC)"
* #00466 "Alanin (U; látková konc. [µmol/l] *)"
* #00467 "Alanin (U; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00468 "Alanin (U; látková konc. [µmol/l] Chromatografie-IEC)"
* #00469 "Alanin (U; látková konc. [µmol/l] Chromatografie-TLC)"
* #00470 "Albumin (Likvor; hmot. konc. [g/l] *)"
* #00471 "Albumin (Likvor; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00472 "Albumin (Likvor; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00473 "Albumin (Likvor; hmot. konc. [g/l] Elektroforéza)"
* #00474 "Albumin (Likvor; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00475 "Albumin (dU; hmot. tok [mg/d] *)"
* #00476 "Albumin (dU; hmot. tok [mg/d] Imunoturbidimetrie)"
* #00477 "Albumin (P; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00478 "Albumin (P; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00479 "Albumin (P; hmot. konc. [g/l] Elektroforéza)"
* #00480 "Albumin (Pleurální tekutina; hmot. konc. [g/l] *)"
* #00481 "Albumin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00482 "Albumin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00483 "Albumin (Pleurální tekutina; hmot. konc. [g/l] Elektroforéza)"
* #00484 "Albumin (Protein(Csf.); hmot. podíl [1] *)"
* #00485 "Albumin (Protein(Csf.); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00486 "Albumin (Protein(Csf.); hmot. podíl [1] Elektroforéza-agaróza)"
* #00487 "Albumin (Protein(Csf.); hmot. podíl [1] Elektroforéza)"
* #00488 "Albumin (Protein(P); hmot. podíl [1] *)"
* #00489 "Albumin (Protein(P); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00490 "Albumin (Protein(P); hmot. podíl [1] Elektroforéza-agaróza)"
* #00491 "Albumin (Protein(P); hmot. podíl [1] Elektroforéza)"
* #00492 "Albumin (Protein(pleurální tekutina); hmot. podíl [1] *)"
* #00493 "Albumin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00494 "Albumin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza-agaróza)"
* #00495 "Albumin (Protein(pleurální tekutina); hmot. podíl [1] Elektroforéza)"
* #00496 "Albumin (Protein(S); hmot. podíl [1] *)"
* #00497 "Albumin (Protein(S); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00498 "Albumin (Protein(S); hmot. podíl [1] Elektroforéza-agaróza)"
* #00499 "Albumin (Protein(S); hmot. podíl [1] Elektroforéza)"
* #00500 "Albumin (Protein(U); hmot. podíl [1] *)"
* #00501 "Albumin (Protein(U); hmot. podíl [1] Elektroforéza-acetylcelulóza)"
* #00502 "Albumin (Protein(U); hmot. podíl [1] Elektroforéza-agaróza)"
* #00503 "Albumin (Protein(U); hmot. podíl [1] Elektroforéza)"
* #00504 "Albumin (S; hmot. konc. [g/l] *)"
* #00505 "Albumin (S; hmot. konc. [g/l] Elektroforéza-acetylcelulóza)"
* #00506 "Albumin (S; hmot. konc. [g/l] Elektroforéza-agaróza)"
* #00507 "Albumin (S; hmot. konc. [g/l] Absorpční spektrofotometrie)"
* #00508 "Albumin (S; hmot. konc. [g/l] Elektroforéza)"
* #00509 "Albumin (U; hmot. konc. [mg/l] *)"
* #00510 "Albumin (U; hmot. konc. [mg/l] Elektroforéza-acetylcelulóza)"
* #00511 "Albumin (U; hmot. konc. [mg/l] Elektroforéza-agaróza)"
* #00512 "Albumin (U; hmot. konc. [mg/l] Elektroforéza)"
* #00513 "Albumin (U; hmot. konc. [mg/l] Imunoturbidimetrie)"
* #00514 "Anti-LCM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00515 "Anti-LCM (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00516 "Anti-LCM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00517 "Anti-LCM (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00518 "ALD (P; konc. katal. akt. [µkat/l] *)"
* #00519 "ALD (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00520 "ALD (S; konc. katal. akt. [µkat/l] *)"
* #00521 "ALD (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00522 "Aldosteron (P; látková konc. [nmol/l] *)"
* #00523 "Aldosteron (P; látková konc. [nmol/l] RIA)"
* #00524 "Aldosteron (S; látková konc. [nmol/l] *)"
* #00525 "Aldosteron (S; látková konc. [nmol/l] RIA)"
* #00526 "Aldosteron (U; látková konc. [nmol/l] *)"
* #00527 "Aldosteron (U; látková konc. [nmol/l] IA)"
* #00528 "Alizarin (Konkrement (močový); objemový podíl [1] Spektroskopie-IR)"
* #00529 "Alizarin (Konkrement (močový); objemový podíl [1] Mikroskopie)"
* #00530 "Anti-Listeria monocytogenes H (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00531 "Anti-Listeria monocytogenes H (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00532 "Anti-Listeria monocytogenes H (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00533 "Anti-Listeria monocytogenes H (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00534 "Anti-Listeria monocytogenes O (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00535 "Anti-Listeria monocytogenes O (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00536 "Anti-Listeria monocytogenes O (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00537 "Anti-Listeria monocytogenes O (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00538 "Allantoin (Konkrement (močový); objemový podíl [1] Spektroskopie-IR)"
* #00539 "Allantoin (Konkrement (močový); objemový podíl [1] Mikroskopie)"
* #00540 "ALP (P; konc. katal. akt. [µkat/l] *)"
* #00541 "ALP (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00542 "ALP (S; konc. katal. akt. [µkat/l] *)"
* #00543 "ALP (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00544 "ALP kostní (ALP(P); podíl katal. akt. [1] *)"
* #00545 "ALP kostní (ALP(P); podíl katal. akt. [1] Elektroforéza)"
* #00546 "ALP kostní (ALP(S); podíl katal. akt. [1] *)"
* #00547 "ALP kostní (ALP(S); podíl katal. akt. [1] Elektroforéza)"
* #00548 "ALP kostní (P; konc. katal. akt. [µkat/l] *)"
* #00549 "ALP kostní (P; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00550 "ALP kostní (S; konc. katal. akt. [µkat/l] *)"
* #00551 "ALP kostní (S; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00552 "ALP kostní typ (protein) (P; hmot. konc. [µg/l] *)"
* #00553 "ALP kostní typ (protein) (P; hmot. konc. [µg/l] IRMA)"
* #00554 "ALP kostní typ (protein) (S; hmot. konc. [µg/l] *)"
* #00555 "ALP kostní typ (protein) (S; hmot. konc. [µg/l] IRMA)"
* #00556 "ALP střevní (ALP(P); podíl katal. akt. [1] *)"
* #00557 "ALP střevní (ALP(S); podíl katal. akt. [1] *)"
* #00558 "ALP střevní (ALP(S); podíl katal. akt. [1] Elektroforéza)"
* #00559 "ALP střevní (P; konc. katal. akt. [µkat/l] *)"
* #00560 "ALP střevní (P; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00561 "ALP střevní (S; konc. katal. akt. [µkat/l] *)"
* #00562 "ALP střevní (S; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00563 "ALP jaterní (ALP(P); podíl katal. akt. [1] *)"
* #00564 "ALP jaterní (ALP(P); podíl katal. akt. [1] Elektroforéza)"
* #00565 "ALP jaterní (ALP(S); podíl katal. akt. [1] *)"
* #00566 "ALP jaterní (ALP(S); podíl katal. akt. [1] Elektroforéza)"
* #00567 "ALP jaterní (P; konc. katal. akt. [µkat/l] *)"
* #00568 "ALP jaterní (P; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00569 "ALP jaterní (S; konc. katal. akt. [µkat/l] *)"
* #00570 "ALP jaterní (S; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00571 "ALP placentární (ALP(P); podíl katal. akt. [1] *)"
* #00572 "ALP placentární (ALP(P); podíl katal. akt. [1] Elektroforéza)"
* #00573 "ALP placentární (ALP(S); podíl katal. akt. [1] *)"
* #00574 "ALP placentární (ALP(S); podíl katal. akt. [1] Elektroforéza)"
* #00575 "ALP placentární (P; konc. katal. akt. [µkat/l] *)"
* #00576 "ALP placentární (P; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00577 "ALP placentární (S; konc. katal. akt. [µkat/l] *)"
* #00578 "ALP placentární (S; konc. katal. akt. [µkat/l] Elektroforéza)"
* #00579 "ALT (P; konc. katal. akt. [µkat/l] *)"
* #00580 "ALT (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00581 "ALT (S; konc. katal. akt. [µkat/l] *)"
* #00582 "ALT (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00583 "Amikacin* (P; látková konc. [µmol/l] *)"
* #00584 "Amikacin* (P; látková konc. [µmol/l] FPIA)"
* #00585 "Amikacin* (S; látková konc. [µmol/l] *)"
* #00586 "Amikacin* (S; látková konc. [µmol/l] FPIA)"
* #00587 "Anti-mikrosomy IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00588 "Anti-mikrosomy IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00589 "Anti-mikrosomy IgG (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00590 "Anti-mikrosomy IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00591 "Anti-mikrosomy IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00592 "Anti-mikrosomy IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00593 "Anti-mikrosomy IgG (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00594 "Anti-mikrosomy IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00595 "Anti-mitochondrie IgA (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00596 "Anti-mitochondrie IgA (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00597 "Anti-mitochondrie IgA (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00598 "Anti-mitochondrie IgA (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00599 "Anti-mitochondrie IgA (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00600 "Anti-mitochondrie IgA (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00601 "Anti-mitochondrie IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00602 "Anti-mitochondrie IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00603 "Anti-mitochondrie IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00604 "Anti-mitochondrie IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00605 "Anti-mitochondrie IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00606 "Anti-mitochondrie IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00607 "Anti-mitochondrie IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00608 "Anti-mitochondrie IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00609 "Anti-mitochondrie IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00610 "Anti-mitochondrie IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00611 "Anti-mitochondrie IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00612 "Anti-mitochondrie IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00613 "Amitriptylin* (P; látková konc. [nmol/l] *)"
* #00614 "Amitriptylin* (P; látková konc. [nmol/l] FPIA)"
* #00615 "Amitriptylin* (S; látková konc. [nmol/l] *)"
* #00616 "Amitriptylin* (S; látková konc. [nmol/l] FPIA)"
* #00617 "Amoniak (P; látková konc. [µmol/l] *)"
* #00618 "Amoniak (P; látková konc. [µmol/l] Absorpční spektrofotom. registr.)"
* #00619 "Amoniak (U; látková konc. [µmol/l] *)"
* #00620 "Amoniak (U; látková konc. [µmol/l] Titrace-potenciometrická)"
* #00621 "Anti-Morbilli (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00622 "Anti-Morbilli (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00623 "Anti-Morbilli (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00624 "Anti-Morbilli (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00625 "Ampicilin sodný (Konkrement (močový); objemový podíl [1] Spektroskopie-IR)"
* #00626 "Ampicilin sodný (Konkrement (močový); objemový podíl [1] Mikroskopie)"
* #00627 "AMS (Duodenální tekutina; konc. katal. akt. [µkat/l] *)"
* #00628 "AMS (Duodenální tekutina; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00629 "AMS (P; konc. katal. akt. [µkat/l] *)"
* #00630 "AMS (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00631 "AMS (Peritoneální tekutina; konc. katal. akt. [µkat/l] *)"
* #00632 "AMS (Peritoneální tekutina; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00633 "AMS (S; konc. katal. akt. [µkat/l] *)"
* #00634 "AMS (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00635 "AMS (U; konc. katal. akt. [µkat/l] *)"
* #00636 "AMS (U; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00637 "Makroamylázový komplex (AMS(P); podíl katal. akt. [1] *)"
* #00638 "Makroamylázový komplex (AMS(P); podíl katal. akt. [1] Absorpční spektrofotometrie)"
* #00639 "Makroamylázový komplex (AMS(S); podíl katal. akt. [1] *)"
* #00640 "Makroamylázový komplex (AMS(S); podíl katal. akt. [1] Absorpční spektrofotometrie)"
* #00641 "AMS pankreatická (P; konc. katal. akt. [µkat/l] *)"
* #00642 "AMS pankreatická (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00643 "AMS pankreatická (S; konc. katal. akt. [µkat/l] *)"
* #00644 "AMS pankreatická (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00645 "Anti-myokardiální IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00646 "Anti-myokardiální IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00647 "Anti-myokardiální IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00648 "Anti-myokardiální IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00649 "Anti-myokardiální IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00650 "Anti-myokardiální IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00651 "Anti-Mycoplasma pneumoniae (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00652 "Anti-Mycoplasma pneumoniae (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00653 "Anti-Mycoplasma pneumoniae (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00654 "Anti-Mycoplasma pneumoniae (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00655 "Anti-Mycobacterium tuberculosis IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00656 "Anti-Mycobacterium tuberculosis IgG (titr) (P; arb. konc. (titr) [arb.j.] IA)"
* #00657 "Anti-Mycobacterium tuberculosis IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00658 "Anti-Mycobacterium tuberculosis IgG (titr) (S; arb. konc. (titr) [arb.j.] IA)"
* #00659 "C-ANCA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00660 "C-ANCA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00661 "C-ANCA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00662 "C-ANCA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00663 "C-ANCA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00664 "C-ANCA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00665 "P-ANCA IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00666 "P-ANCA IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00667 "P-ANCA IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00668 "P-ANCA IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00669 "P-ANCA IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00670 "P-ANCA IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00671 "Anti-nukleolární IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00672 "Anti-nukleolární IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00673 "Anti-nukleolární IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00674 "Anti-nukleolární IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00675 "Anti-nukleolární IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00676 "Anti-nukleolární IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00677 "Anti-nukleární IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00678 "Anti-nukleární IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00679 "Anti-nukleární IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00680 "Anti-nukleární IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00681 "Anti-nukleární IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00682 "Anti-nukleární IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00683 "Angiotenzin (S; arb. látková konc. [mU/l] *)"
* #00684 "Anti-parietální buňky IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00685 "Anti-parietální buňky IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00686 "Anti-parietální buňky IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00687 "Anti-parietální buňky IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00688 "Anti-parietální buňky IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00689 "Anti-parietální buňky IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00690 "Anti-Mumps virus IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00691 "Anti-Mumps virus IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00692 "Anti-Mumps virus IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00693 "Anti-Mumps virus IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00694 "Anti-Mumps virus IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00695 "Anti-Mumps virus IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00696 "Anti-Mumps virus IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00697 "Anti-Mumps virus IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00698 "Anti-Mumps virus IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00699 "Anti-Mumps virus IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00700 "Anti-Mumps virus IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00701 "Anti-Mumps virus IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00702 "Anti-Mumps virus (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00703 "Anti-Mumps virus (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00704 "Anti-Mumps virus (titr) (P; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00705 "Anti-Mumps virus (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00706 "Anti-Mumps virus (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00707 "Anti-Mumps virus (titr) (S; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00708 "Anti-parainfluenza 1 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00709 "Anti-parainfluenza 1 (titr) (P; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00710 "Anti-parainfluenza 1 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00711 "Anti-parainfluenza 1 (titr) (S; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00712 "Anti-parainfluenza 2 IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00713 "Anti-parainfluenza 2 IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00714 "Anti-parainfluenza 2 IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00715 "Anti-parainfluenza 2 IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00716 "Anti-parainfluenza 2 IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00717 "Anti-parainfluenza 2 IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00718 "Anti-parainfluenza 2 IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00719 "Anti-parainfluenza 2 IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00720 "Anti-parainfluenza 2 IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00721 "Anti-parainfluenza 2 IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00722 "Anti-parainfluenza 2 IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00723 "Anti-parainfluenza 2 IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00724 "Anti-parainfluenza 2 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00725 "Anti-parainfluenza 2 (titr) (P; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00726 "Anti-parainfluenza 2 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00727 "Anti-parainfluenza 2 (titr) (S; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00728 "Anti-parainfluenza 3 IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00729 "Anti-parainfluenza 3 IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00730 "Anti-parainfluenza 3 IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00731 "Anti-parainfluenza 3 IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00732 "Anti-parainfluenza 3 IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00733 "Anti-parainfluenza 3 IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00734 "Anti-parainfluenza 3 IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00735 "Anti-parainfluenza 3 IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00736 "Anti-parainfluenza 3 IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00737 "Anti-parainfluenza 3 IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00738 "Anti-parainfluenza 3 IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00739 "Anti-parainfluenza 3 IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00740 "Anti-parainfluenza 3 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00741 "Anti-parainfluenza 3 (titr) (P; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00742 "Anti-parainfluenza 3 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00743 "Anti-parainfluenza 3 (titr) (S; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00744 "Apolipoprotein AI (Žluč; hmot. konc. [mg/l] *)"
* #00745 "Apolipoprotein AI (Žluč; hmot. konc. [mg/l] IA)"
* #00746 "Apolipoprotein AI (P; hmot. konc. [g/l] *)"
* #00747 "Apolipoprotein AI (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00748 "Apolipoprotein AI (S; hmot. konc. [g/l] *)"
* #00749 "Apolipoprotein AI (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00750 "Apolipoprotein AII (Žluč; hmot. konc. [mg/l] *)"
* #00751 "Apolipoprotein AII (Žluč; hmot. konc. [mg/l] IA)"
* #00752 "Apolipoprotein AII (P; hmot. konc. [g/l] *)"
* #00753 "Apolipoprotein AII (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00754 "Apolipoprotein AII (S; hmot. konc. [g/l] *)"
* #00755 "Apolipoprotein AII (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00756 "Apolipoprotein AIV (P; hmot. konc. [g/l] *)"
* #00757 "Apolipoprotein AIV (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00758 "Apolipoprotein B (Žluč; hmot. konc. [mg/l] *)"
* #00759 "Apolipoprotein B (Žluč; hmot. konc. [mg/l] IA)"
* #00760 "Apolipoprotein B (P; hmot. konc. [g/l] *)"
* #00761 "Apolipoprotein B (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00762 "Apolipoprotein B (S; hmot. konc. [g/l] *)"
* #00763 "Apolipoprotein B (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00764 "Apolipoprotein B100 (P; hmot. konc. [g/l] *)"
* #00765 "Apolipoprotein B100 (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00766 "Apolipoprotein B100 (S; hmot. konc. [g/l] *)"
* #00767 "Apolipoprotein B100 (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00768 "Apolipoprotein B150 (P; hmot. konc. [g/l] *)"
* #00769 "Apolipoprotein B150 (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00770 "Apolipoprotein B150 (S; hmot. konc. [g/l] *)"
* #00771 "Apolipoprotein B150 (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00772 "Apolipoprotein B48 (P; hmot. konc. [g/l] *)"
* #00773 "Apolipoprotein B48 (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00774 "Apolipoprotein B48 (S; hmot. konc. [g/l] *)"
* #00775 "Apolipoprotein B48 (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00776 "Apolipoprotein CI (P; hmot. konc. [g/l] *)"
* #00777 "Apolipoprotein CI (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00778 "Apolipoprotein CI (S; hmot. konc. [g/l] *)"
* #00779 "Apolipoprotein CI (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00780 "Apolipoprotein CII (Žluč; hmot. konc. [mg/l] *)"
* #00781 "Apolipoprotein CII (Žluč; hmot. konc. [mg/l] IA)"
* #00782 "Apolipoprotein CII (P; hmot. konc. [g/l] *)"
* #00783 "Apolipoprotein CII (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00784 "Apolipoprotein CII (S; hmot. konc. [g/l] *)"
* #00785 "Apolipoprotein CII (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00786 "Apolipoprotein CIII (Žluč; hmot. konc. [mg/l] *)"
* #00787 "Apolipoprotein CIII (Žluč; hmot. konc. [mg/l] IA)"
* #00788 "Apolipoprotein CIII (P; hmot. konc. [g/l] *)"
* #00789 "Apolipoprotein CIII (P; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00790 "Apolipoprotein CIII (S; hmot. konc. [g/l] *)"
* #00791 "Apolipoprotein CIII (S; hmot. konc. [g/l] Imunoturbidimetrie)"
* #00792 "Apolipoprotein E (P; hmot. konc. [g/l] *)"
* #00793 "Apolipoprotein E (P; hmot. konc. [g/l] IA)"
* #00794 "Apolipoprotein E (S; hmot. konc. [g/l] *)"
* #00795 "Apolipoprotein E (S; hmot. konc. [g/l] IA)"
* #00796 "Aragonit (Konkrement (močový); objemový podíl [1] Spektroskopie-IR)"
* #00797 "Aragonit (Konkrement (močový); objemový podíl [1] Mikroskopie)"
* #00798 "Arginin (Likvor; látková konc. [µmol/l] *)"
* #00799 "Arginin (Likvor; látková konc. [µmol/l] Chromatografie-IEC)"
* #00800 "Arginin (dU; látkový tok [µmol/d] *)"
* #00801 "Arginin (dU; látkový tok [µmol/d] Chromatografie-HPLC)"
* #00802 "Arginin (dU; látkový tok [µmol/d] Chromatografie-IEC)"
* #00803 "Arginin (dU; látkový tok [µmol/d] Chromatografie-TLC)"
* #00804 "Arginin (P; látková konc. [µmol/l] *)"
* #00805 "Arginin (P; látková konc. [µmol/l] Chromatografie-IEC)"
* #00806 "Arginin (S; látková konc. [µmol/l] *)"
* #00807 "Arginin (S; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00808 "Arginin (S; látková konc. [µmol/l] Chromatografie-IEC)"
* #00809 "Arginin (S; látková konc. [µmol/l] Chromatografie-TLC)"
* #00810 "Arginin (U; látková konc. [µmol/l] *)"
* #00811 "Arginin (U; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00812 "Arginin (U; látková konc. [µmol/l] Chromatografie-IEC)"
* #00813 "Arginin (U; látková konc. [µmol/l] Chromatografie-TLC)"
* #00814 "Argináza (Žaludek(biopsie); obsah katal. akt. [µkat/kg] *)"
* #00815 "Argináza (Tkáň(biopsie); obsah katal. akt. [µkat/kg] Absorpční spektrofotometrie)"
* #00816 "Anti-RS virus (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00817 "Anti-RS virus (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00818 "Anti-RS virus (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00819 "Anti-RS virus (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00820 "Anti-Rubella (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00821 "Anti-Rubella (titr) (P; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00822 "Anti-Rubella (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00823 "Anti-Rubella (titr) (S; arb. konc. (titr) [arb.j.] Inhibice hemaglutinace)"
* #00824 "Anti-Salmonella H 1,2 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00825 "Anti-Salmonella H 1,2 (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00826 "Anti-Salmonella H 1,2 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00827 "Anti-Salmonella H 1,2 (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00828 "Anti-Salmonella H b (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00829 "Anti-Salmonella H b (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00830 "Anti-Salmonella H b (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00831 "Anti-Salmonella H b (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00832 "Anti-Salmonella H d (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00833 "Anti-Salmonella H d (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00834 "Anti-Salmonella H d (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00835 "Anti-Salmonella H d (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00836 "Anti-Salmonella H gm (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00837 "Anti-Salmonella H gm (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00838 "Anti-Salmonella H gm (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00839 "Anti-Salmonella H gm (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00840 "Anti-Salmonella O 4 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00841 "Anti-Salmonella O 4 (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00842 "Anti-Salmonella O 4 (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00843 "Anti-Salmonella O 4 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00844 "Anti-Salmonella O 4 (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00845 "Anti-Salmonella O 4 (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00846 "Anti-Salmonella O 6,7 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00847 "Anti-Salmonella O 6,7 (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00848 "Anti-Salmonella O 6,7 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00849 "Anti-Salmonella O 6,7 (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00850 "Anti-Salmonella O 9 (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00851 "Anti-Salmonella O 9 (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00852 "Anti-Salmonella O 9 (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00853 "Anti-Salmonella O 9 (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00854 "Anti-Salmonella O 9 (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00855 "Anti-Salmonella O 9 (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00856 "Anti-Salmonella Vi (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00857 "Anti-Salmonella Vi (titr) (P; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00858 "Anti-Salmonella Vi (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00859 "Anti-Salmonella Vi (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00860 "Anti-Salmonella Vi (titr) (S; arb. konc. (titr) [arb.j.] Aglutinace)"
* #00861 "Anti-Salmonella Vi (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00862 "Anti-streptolysin O (P; arb. látková konc. [kU/l] *)"
* #00863 "Anti-streptolysin O (P; arb. látková konc. [kU/l] Inhibice hemolýzy)"
* #00864 "Anti-streptolysin O (P; arb. látková konc. [kU/l] Nefelometrie)"
* #00865 "Anti-streptolysin O (S; arb. látková konc. [kU/l] *)"
* #00866 "Anti-streptolysin O (S; arb. látková konc. [kU/l] Inhibice hemolýzy)"
* #00867 "Anti-streptolysin O (S; arb. látková konc. [kU/l] Nefelometrie)"
* #00868 "Anti-hladký sval IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00869 "Anti-hladký sval IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00870 "Anti-hladký sval IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00871 "Anti-hladký sval IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00872 "Anti-hladký sval IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00873 "Anti-hladký sval IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00874 "Asparagin (Likvor; látková konc. [µmol/l] *)"
* #00875 "Asparagin (Likvor; látková konc. [µmol/l] Chromatografie-IEC)"
* #00876 "Asparagin (dU; látkový tok [µmol/d] *)"
* #00877 "Asparagin (dU; látkový tok [µmol/d] Chromatografie-HPLC)"
* #00878 "Asparagin (dU; látkový tok [µmol/d] Chromatografie-IEC)"
* #00879 "Asparagin (dU; látkový tok [µmol/d] Chromatografie-TLC)"
* #00880 "Asparagin (P; látková konc. [µmol/l] *)"
* #00881 "Asparagin (P; látková konc. [µmol/l] Chromatografie-IEC)"
* #00882 "Asparagin (S; látková konc. [µmol/l] *)"
* #00883 "Asparagin (S; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00884 "Asparagin (S; látková konc. [µmol/l] Chromatografie-IEC)"
* #00885 "Asparagin (S; látková konc. [µmol/l] Chromatografie-TLC)"
* #00886 "Asparagin (U; látková konc. [µmol/l] *)"
* #00887 "Asparagin (U; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00888 "Asparagin (U; látková konc. [µmol/l] Chromatografie-IEC)"
* #00889 "Asparagin (U; látková konc. [µmol/l] Chromatografie-TLC)"
* #00890 "Aspartát (Likvor; látková konc. [µmol/l] *)"
* #00891 "Aspartát (Likvor; látková konc. [µmol/l] Chromatografie-IEC)"
* #00892 "Aspartát (dU; látkový tok [µmol/d] *)"
* #00893 "Aspartát (dU; látkový tok [µmol/d] Chromatografie-HPLC)"
* #00894 "Aspartát (dU; látkový tok [µmol/d] Chromatografie-IEC)"
* #00895 "Aspartát (dU; látkový tok [µmol/d] Chromatografie-TLC)"
* #00896 "Aspartát (P; látková konc. [µmol/l] *)"
* #00897 "Aspartát (P; látková konc. [µmol/l] Chromatografie-IEC)"
* #00898 "Aspartát (S; látková konc. [µmol/l] *)"
* #00899 "Aspartát (S; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00900 "Aspartát (S; látková konc. [µmol/l] Chromatografie-IEC)"
* #00901 "Aspartát (S; látková konc. [µmol/l] Chromatografie-TLC)"
* #00902 "Aspartát (U; látková konc. [µmol/l] *)"
* #00903 "Aspartát (U; látková konc. [µmol/l] Chromatografie-HPLC)"
* #00904 "Aspartát (U; látková konc. [µmol/l] Chromatografie-IEC)"
* #00905 "Aspartát (U; látková konc. [µmol/l] Chromatografie-TLC)"
* #00906 "Anti-spermie IgA (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00907 "Anti-spermie IgA (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00908 "Anti-spermie IgA (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00909 "Anti-spermie IgA (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00910 "Anti-spermie IgA (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00911 "Anti-spermie IgA (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00912 "Anti-spermie IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00913 "Anti-spermie IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00914 "Anti-spermie IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00915 "Anti-spermie IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00916 "Anti-spermie IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00917 "Anti-spermie IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00918 "AST (P; konc. katal. akt. [µkat/l] *)"
* #00919 "AST (P; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00920 "AST (S; konc. katal. akt. [µkat/l] *)"
* #00921 "AST (S; konc. katal. akt. [µkat/l] Absorpční spektrofotometrie)"
* #00922 "Anti-stafylolysin alfa (P; arb. látková konc. [kU/l] *)"
* #00923 "Anti-stafylolysin alfa (P; arb. látková konc. [kU/l] Inhibice hemolýzy)"
* #00924 "Anti-stafylolysin alfa (S; arb. látková konc. [kU/l] *)"
* #00925 "Anti-stafylolysin alfa (S; arb. látková konc. [kU/l] Inhibice hemolýzy)"
* #00926 "Anti-příčně pruhovaný sval IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00927 "Anti-příčně pruhovaný sval IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00928 "Anti-příčně pruhovaný sval IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00929 "Anti-příčně pruhovaný sval IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00930 "Anti-příčně pruhovaný sval IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00931 "Anti-příčně pruhovaný sval IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00932 "Anti-TBE IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00933 "Anti-TBE IgG (titr) (P; arb. konc. (titr) [arb.j.] IA)"
* #00934 "Anti-TBE IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00935 "Anti-TBE IgG (titr) (S; arb. konc. (titr) [arb.j.] IA)"
* #00936 "Anti-TBE IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00937 "Anti-TBE IgM (titr) (P; arb. konc. (titr) [arb.j.] IA)"
* #00938 "Anti-TBE IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00939 "Anti-TBE IgM (titr) (S; arb. konc. (titr) [arb.j.] IA)"
* #00940 "Anti-TBE (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00941 "Anti-TBE (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00942 "Anti-TBE (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00943 "Anti-TBE (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00944 "Anti-tyreoglobulin IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00945 "Anti-tyreoglobulin IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00946 "Anti-tyreoglobulin IgG (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00947 "Anti-tyreoglobulin IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00948 "Anti-tyreoglobulin IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00949 "Anti-tyreoglobulin IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00950 "Anti-tyreoglobulin IgG (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00951 "Anti-tyreoglobulin IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00952 "Anti-Toxoplasma gondii IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00953 "Anti-Toxoplasma gondii IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00954 "Anti-Toxoplasma gondii IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00955 "Anti-Toxoplasma gondii IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00956 "Anti-Toxoplasma gondii IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00957 "Anti-Toxoplasma gondii IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00958 "Anti-Toxoplasma gondii IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00959 "Anti-Toxoplasma gondii IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00960 "Anti-Toxoplasma gondii IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00961 "Anti-Toxoplasma gondii IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00962 "Anti-Toxoplasma gondii IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00963 "Anti-Toxoplasma gondii IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00964 "Anti-Toxoplasma gondii (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00965 "Anti-Toxoplasma gondii (titr) (P; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00966 "Anti-Toxoplasma gondii (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00967 "Anti-Toxoplasma gondii (titr) (S; arb. konc. (titr) [arb.j.] Komplement-fixační reakce)"
* #00968 "Anti-Treponema pallidum IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00969 "Anti-Treponema pallidum IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00970 "Anti-Treponema pallidum IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00971 "Anti-Treponema pallidum IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00972 "Anti-Treponema pallidum IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00973 "Anti-Treponema pallidum IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00974 "Anti-Treponema pallidum IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00975 "Anti-Treponema pallidum IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00976 "Anti-Treponema pallidum (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00977 "Anti-Treponema pallidum (titr) (P; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00978 "Anti-Treponema pallidum (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00979 "Anti-Treponema pallidum (titr) (S; arb. konc. (titr) [arb.j.] Hemaglutinace)"
* #00980 "Vitamin A (zrušen) (S; látková konc. [µmol/l] *)"
* #00981 "Vitamin A (zrušen) (S; látková konc. [µmol/l] Absorpční spektrofotom. registr.)"
* #00982 "Anti-VZV IgA (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00983 "Anti-VZV IgA (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00984 "Anti-VZV IgA (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00985 "Anti-VZV IgA (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00986 "Anti-VZV IgA (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00987 "Anti-VZV IgA (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00988 "Anti-VZV IgG (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00989 "Anti-VZV IgG (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00990 "Anti-VZV IgG (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00991 "Anti-VZV IgG (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00992 "Anti-VZV IgG (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00993 "Anti-VZV IgG (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00994 "Anti-VZV IgM (titr) (P; arb. konc. (titr) [arb.j.] *)"
* #00995 "Anti-VZV IgM (titr) (P; arb. konc. (titr) [arb.j.] ELISA)"
* #00996 "Anti-VZV IgM (titr) (P; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
* #00997 "Anti-VZV IgM (titr) (S; arb. konc. (titr) [arb.j.] *)"
* #00998 "Anti-VZV IgM (titr) (S; arb. konc. (titr) [arb.j.] ELISA)"
* #00999 "Anti-VZV IgM (titr) (S; arb. konc. (titr) [arb.j.] Mikroskopie - IF nepřímá)"
