ValueSet: IdCardUri
Id: idcard-uri
Title: "ID Card URIs"
Description: "A country specific URI for personal Id card numbers"
* ^url = "https://hl7.cz/terminology/ValueSet/idcard-uri"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-01-01"
* ^publisher = "HL7 Czech Republic"
* ^language = #cs
* ^jurisdiction = urn:iso:std:iso:3166#CZ "Czechia"
* insert SetFmmandStatusRule(2, trial-use)

* $uri#https://hl7.cz/fhir/sid/idcard-AFG "Afghánistán"
* $uri#https://hl7.cz/fhir/sid/idcard-ALB "Albánie"
* $uri#https://hl7.cz/fhir/sid/idcard-DZA "Alžírsko"
* $uri#https://hl7.cz/fhir/sid/idcard-ASM "Americká Samoa"
* $uri#https://hl7.cz/fhir/sid/idcard-AND "Andorra"
* $uri#https://hl7.cz/fhir/sid/idcard-AGO "Angola"
* $uri#https://hl7.cz/fhir/sid/idcard-AIA "Anguilla"
* $uri#https://hl7.cz/fhir/sid/idcard-ATA "Antarktida"
* $uri#https://hl7.cz/fhir/sid/idcard-ATG "Antigua a Barbuda"
* $uri#https://hl7.cz/fhir/sid/idcard-ARG "Argentina"
* $uri#https://hl7.cz/fhir/sid/idcard-ARM "Arménie"
* $uri#https://hl7.cz/fhir/sid/idcard-ABW "Aruba"
* $uri#https://hl7.cz/fhir/sid/idcard-AUS "Austrálie"
* $uri#https://hl7.cz/fhir/sid/idcard-AUT "Rakousko"
* $uri#https://hl7.cz/fhir/sid/idcard-AZE "Ázerbájdžán"
* $uri#https://hl7.cz/fhir/sid/idcard-BHS "Bahamy"
* $uri#https://hl7.cz/fhir/sid/idcard-BHR "Bahrajn"
* $uri#https://hl7.cz/fhir/sid/idcard-BGD "Bangladéš"
* $uri#https://hl7.cz/fhir/sid/idcard-BRB "Barbados"
* $uri#https://hl7.cz/fhir/sid/idcard-BLR "Bělorusko"
* $uri#https://hl7.cz/fhir/sid/idcard-BEL "Belgie"
* $uri#https://hl7.cz/fhir/sid/idcard-BLZ "Belize"
* $uri#https://hl7.cz/fhir/sid/idcard-BEN "Benin"
* $uri#https://hl7.cz/fhir/sid/idcard-BMU "Bermudy"
* $uri#https://hl7.cz/fhir/sid/idcard-BTN "Bhútán"
* $uri#https://hl7.cz/fhir/sid/idcard-BOL "Bolívie"
* $uri#https://hl7.cz/fhir/sid/idcard-BES "Bonaire, Svatý Eustach a Saba"
* $uri#https://hl7.cz/fhir/sid/idcard-BIH "Bosna a Hercegovina"
* $uri#https://hl7.cz/fhir/sid/idcard-BWA "Botswana"
* $uri#https://hl7.cz/fhir/sid/idcard-BVT "Bouvetův ostrov"
* $uri#https://hl7.cz/fhir/sid/idcard-BRA "Brazílie"
* $uri#https://hl7.cz/fhir/sid/idcard-IOT "Britské indickooceánské území"
* $uri#https://hl7.cz/fhir/sid/idcard-BRN "Brunej"
* $uri#https://hl7.cz/fhir/sid/idcard-BGR "Bulharsko"
* $uri#https://hl7.cz/fhir/sid/idcard-BFA "Burkina Faso"
* $uri#https://hl7.cz/fhir/sid/idcard-BDI "Burundi"
* $uri#https://hl7.cz/fhir/sid/idcard-CPV "Burundi"
* $uri#https://hl7.cz/fhir/sid/idcard-KHM "Kambodža"
* $uri#https://hl7.cz/fhir/sid/idcard-CMR "Kamerun"
* $uri#https://hl7.cz/fhir/sid/idcard-CAN "Kanada"
* $uri#https://hl7.cz/fhir/sid/idcard-CYM "Kajmanské ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-CAF "Středoafrická republika"
* $uri#https://hl7.cz/fhir/sid/idcard-TCD "Čad"
* $uri#https://hl7.cz/fhir/sid/idcard-CHL "Chile"
* $uri#https://hl7.cz/fhir/sid/idcard-CHN "Čína"
* $uri#https://hl7.cz/fhir/sid/idcard-CXR "Vánoční ostrov"
* $uri#https://hl7.cz/fhir/sid/idcard-CCK "Kokosové (Keelingovy) ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-COL "Kolumbie"
* $uri#https://hl7.cz/fhir/sid/idcard-COM "Komory"
* $uri#https://hl7.cz/fhir/sid/idcard-COD "Konžská republika"
* $uri#https://hl7.cz/fhir/sid/idcard-COG "Konžská republika"
* $uri#https://hl7.cz/fhir/sid/idcard-COK "Cookovy ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-CRI "Kostarika"
* $uri#https://hl7.cz/fhir/sid/idcard-HRV "Chorvatsko"
* $uri#https://hl7.cz/fhir/sid/idcard-CUB "Kuba"
* $uri#https://hl7.cz/fhir/sid/idcard-CUW "Curaçao"
* $uri#https://hl7.cz/fhir/sid/idcard-CYP "Kypr"
* $uri#https://hl7.cz/fhir/sid/idcard-CZE "Česko"
* $uri#https://hl7.cz/fhir/sid/idcard-CIV "Pobřeží slonoviny"
* $uri#https://hl7.cz/fhir/sid/idcard-DNK "Dánsko"
* $uri#https://hl7.cz/fhir/sid/idcard-DJI "Džibutsko"
* $uri#https://hl7.cz/fhir/sid/idcard-DMA "Dominika"
* $uri#https://hl7.cz/fhir/sid/idcard-DOM "Dominikánská republika"
* $uri#https://hl7.cz/fhir/sid/idcard-ECU "Ekvádor"
* $uri#https://hl7.cz/fhir/sid/idcard-EGY "Egypt"
* $uri#https://hl7.cz/fhir/sid/idcard-SLV "Salvador"
* $uri#https://hl7.cz/fhir/sid/idcard-GNQ "Rovníková Guinea"
* $uri#https://hl7.cz/fhir/sid/idcard-ERI "Eritrea"
* $uri#https://hl7.cz/fhir/sid/idcard-EST "Estonsko"
* $uri#https://hl7.cz/fhir/sid/idcard-SWZ "Estonsko"
* $uri#https://hl7.cz/fhir/sid/idcard-ETH "Etiopie"
* $uri#https://hl7.cz/fhir/sid/idcard-FLK "Falklandy"
* $uri#https://hl7.cz/fhir/sid/idcard-FRO "Faerské ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-FJI "Fidži"
* $uri#https://hl7.cz/fhir/sid/idcard-FIN "Finsko"
* $uri#https://hl7.cz/fhir/sid/idcard-FRA "Francie"
* $uri#https://hl7.cz/fhir/sid/idcard-GUF "Francouzská Guyana"
* $uri#https://hl7.cz/fhir/sid/idcard-PYF "Francouzská Polynésie"
* $uri#https://hl7.cz/fhir/sid/idcard-ATF "Francouzská jižní a antarktická území"
* $uri#https://hl7.cz/fhir/sid/idcard-GAB "Gabon"
* $uri#https://hl7.cz/fhir/sid/idcard-GMB "Gambie"
* $uri#https://hl7.cz/fhir/sid/idcard-GEO "Gruzie"
* $uri#https://hl7.cz/fhir/sid/idcard-DEU "Německo"
* $uri#https://hl7.cz/fhir/sid/idcard-GHA "Ghana"
* $uri#https://hl7.cz/fhir/sid/idcard-GIB "Gibraltar"
* $uri#https://hl7.cz/fhir/sid/idcard-GRC "Řecko"
* $uri#https://hl7.cz/fhir/sid/idcard-GRL "Grónsko"
* $uri#https://hl7.cz/fhir/sid/idcard-GRD "Grenada"
* $uri#https://hl7.cz/fhir/sid/idcard-GLP "Guadeloupe"
* $uri#https://hl7.cz/fhir/sid/idcard-GUM "Guam"
* $uri#https://hl7.cz/fhir/sid/idcard-GTM "Guatemala"
* $uri#https://hl7.cz/fhir/sid/idcard-GGY "Guernsey"
* $uri#https://hl7.cz/fhir/sid/idcard-GIN "Guinea"
* $uri#https://hl7.cz/fhir/sid/idcard-GNB "Guinea-Bissau"
* $uri#https://hl7.cz/fhir/sid/idcard-GUY "Guyana"
* $uri#https://hl7.cz/fhir/sid/idcard-HTI "Haiti"
* $uri#https://hl7.cz/fhir/sid/idcard-HMD "Heardův ostrov a MacDonaldovy ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-VAT "Vatikán"
* $uri#https://hl7.cz/fhir/sid/idcard-HND "Honduras"
* $uri#https://hl7.cz/fhir/sid/idcard-HKG "Hongkong"
* $uri#https://hl7.cz/fhir/sid/idcard-HUN "Maďarsko"
* $uri#https://hl7.cz/fhir/sid/idcard-ISL "Island"
* $uri#https://hl7.cz/fhir/sid/idcard-IND "Indie"
* $uri#https://hl7.cz/fhir/sid/idcard-IDN "Indonésie"
* $uri#https://hl7.cz/fhir/sid/idcard-IRN "Írán"
* $uri#https://hl7.cz/fhir/sid/idcard-IRQ "Irák"
* $uri#https://hl7.cz/fhir/sid/idcard-IRL "Irsko"
* $uri#https://hl7.cz/fhir/sid/idcard-IMN "Man"
* $uri#https://hl7.cz/fhir/sid/idcard-ISR "Izrael"
* $uri#https://hl7.cz/fhir/sid/idcard-ITA "Itálie"
* $uri#https://hl7.cz/fhir/sid/idcard-JAM "Jamajka"
* $uri#https://hl7.cz/fhir/sid/idcard-JPN "Japonsko"
* $uri#https://hl7.cz/fhir/sid/idcard-JEY "Jersey"
* $uri#https://hl7.cz/fhir/sid/idcard-JOR "Jordánsko"
* $uri#https://hl7.cz/fhir/sid/idcard-KAZ "Kazachstán"
* $uri#https://hl7.cz/fhir/sid/idcard-KEN "Keňa"
* $uri#https://hl7.cz/fhir/sid/idcard-KIR "Kiribati"
* $uri#https://hl7.cz/fhir/sid/idcard-PRK "Korejská lidově demokratická republika"
* $uri#https://hl7.cz/fhir/sid/idcard-KOR "Korejská lidově demokratická republika"
* $uri#https://hl7.cz/fhir/sid/idcard-KWT "Kuvajt"
* $uri#https://hl7.cz/fhir/sid/idcard-KGZ "Kyrgyzstán"
* $uri#https://hl7.cz/fhir/sid/idcard-LAO "Laos"
* $uri#https://hl7.cz/fhir/sid/idcard-LVA "Lotyšsko"
* $uri#https://hl7.cz/fhir/sid/idcard-LBN "Libanon"
* $uri#https://hl7.cz/fhir/sid/idcard-LSO "Lesotho"
* $uri#https://hl7.cz/fhir/sid/idcard-LBR "Libérie"
* $uri#https://hl7.cz/fhir/sid/idcard-LBY "Libye"
* $uri#https://hl7.cz/fhir/sid/idcard-LIE "Lichtenštejnsko"
* $uri#https://hl7.cz/fhir/sid/idcard-LTU "Litva"
* $uri#https://hl7.cz/fhir/sid/idcard-LUX "Lucembursko"
* $uri#https://hl7.cz/fhir/sid/idcard-MAC "Macao"
* $uri#https://hl7.cz/fhir/sid/idcard-MDG "Madagaskar"
* $uri#https://hl7.cz/fhir/sid/idcard-MWI "Malawi"
* $uri#https://hl7.cz/fhir/sid/idcard-MYS "Malajsie"
* $uri#https://hl7.cz/fhir/sid/idcard-MDV "Maledivy"
* $uri#https://hl7.cz/fhir/sid/idcard-MLI "Mali"
* $uri#https://hl7.cz/fhir/sid/idcard-MLT "Malta"
* $uri#https://hl7.cz/fhir/sid/idcard-MHL "Marshallovy ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-MTQ "Martinik"
* $uri#https://hl7.cz/fhir/sid/idcard-MRT "Mauritánie"
* $uri#https://hl7.cz/fhir/sid/idcard-MUS "Mauricius"
* $uri#https://hl7.cz/fhir/sid/idcard-MYT "Mayotte"
* $uri#https://hl7.cz/fhir/sid/idcard-MEX "Mexiko"
* $uri#https://hl7.cz/fhir/sid/idcard-FSM "Mikronésie"
* $uri#https://hl7.cz/fhir/sid/idcard-MDA "Mikronésie"
* $uri#https://hl7.cz/fhir/sid/idcard-MCO "Monako"
* $uri#https://hl7.cz/fhir/sid/idcard-MNG "Mongolsko"
* $uri#https://hl7.cz/fhir/sid/idcard-MNE "Černá Hora"
* $uri#https://hl7.cz/fhir/sid/idcard-MSR "Montserrat"
* $uri#https://hl7.cz/fhir/sid/idcard-MAR "Maroko"
* $uri#https://hl7.cz/fhir/sid/idcard-MOZ "Mosambik"
* $uri#https://hl7.cz/fhir/sid/idcard-MMR "Myanmar"
* $uri#https://hl7.cz/fhir/sid/idcard-NAM "Namibie"
* $uri#https://hl7.cz/fhir/sid/idcard-NRU "Nauru"
* $uri#https://hl7.cz/fhir/sid/idcard-NPL "Nepál"
* $uri#https://hl7.cz/fhir/sid/idcard-NLD "Nizozemsko"
* $uri#https://hl7.cz/fhir/sid/idcard-NCL "Nová Kaledonie"
* $uri#https://hl7.cz/fhir/sid/idcard-NZL "Nový Zéland"
* $uri#https://hl7.cz/fhir/sid/idcard-NIC "Nikaragua"
* $uri#https://hl7.cz/fhir/sid/idcard-NER "Niger"
* $uri#https://hl7.cz/fhir/sid/idcard-NGA "Nigérie"
* $uri#https://hl7.cz/fhir/sid/idcard-NIU "Niue"
* $uri#https://hl7.cz/fhir/sid/idcard-NFK "Norfolk"
* $uri#https://hl7.cz/fhir/sid/idcard-MKD "Norfolk"
* $uri#https://hl7.cz/fhir/sid/idcard-MNP "Severní Mariany"
* $uri#https://hl7.cz/fhir/sid/idcard-NOR "Norsko"
* $uri#https://hl7.cz/fhir/sid/idcard-OMN "Omán"
* $uri#https://hl7.cz/fhir/sid/idcard-PAK "Pákistán"
* $uri#https://hl7.cz/fhir/sid/idcard-PLW "Palau"
* $uri#https://hl7.cz/fhir/sid/idcard-PSE "Palestina"
* $uri#https://hl7.cz/fhir/sid/idcard-PAN "Panama"
* $uri#https://hl7.cz/fhir/sid/idcard-PNG "Papua Nová Guinea"
* $uri#https://hl7.cz/fhir/sid/idcard-PRY "Paraguay"
* $uri#https://hl7.cz/fhir/sid/idcard-PER "Peru"
* $uri#https://hl7.cz/fhir/sid/idcard-PHL "Filipíny"
* $uri#https://hl7.cz/fhir/sid/idcard-PCN "Pitcairn"
* $uri#https://hl7.cz/fhir/sid/idcard-POL "Polsko"
* $uri#https://hl7.cz/fhir/sid/idcard-PRT "Portugalsko"
* $uri#https://hl7.cz/fhir/sid/idcard-PRI "Portoriko"
* $uri#https://hl7.cz/fhir/sid/idcard-QAT "Katar"
* $uri#https://hl7.cz/fhir/sid/idcard-ROU "Rumunsko"
* $uri#https://hl7.cz/fhir/sid/idcard-RUS "Rusko"
* $uri#https://hl7.cz/fhir/sid/idcard-RWA "Rwanda"
* $uri#https://hl7.cz/fhir/sid/idcard-REU "Réunion"
* $uri#https://hl7.cz/fhir/sid/idcard-BLM "Svatý Bartoloměj"
* $uri#https://hl7.cz/fhir/sid/idcard-SHN "Svatá Helena"
* $uri#https://hl7.cz/fhir/sid/idcard-KNA "Svatý Kryštof a Nevis"
* $uri#https://hl7.cz/fhir/sid/idcard-LCA "Svatá Lucie"
* $uri#https://hl7.cz/fhir/sid/idcard-MAF "Svatý Martin (FR)"
* $uri#https://hl7.cz/fhir/sid/idcard-SPM "Saint Pierre a Miquelon"
* $uri#https://hl7.cz/fhir/sid/idcard-VCT "Svatý Vincenc a Grenadiny"
* $uri#https://hl7.cz/fhir/sid/idcard-WSM "Samoa"
* $uri#https://hl7.cz/fhir/sid/idcard-SMR "San Marino"
* $uri#https://hl7.cz/fhir/sid/idcard-STP "Svatý Tomáš a Princův ostrov"
* $uri#https://hl7.cz/fhir/sid/idcard-SAU "Saúdská Arábie"
* $uri#https://hl7.cz/fhir/sid/idcard-SEN "Senegal"
* $uri#https://hl7.cz/fhir/sid/idcard-SRB "Srbsko"
* $uri#https://hl7.cz/fhir/sid/idcard-SYC "Seychely"
* $uri#https://hl7.cz/fhir/sid/idcard-SLE "Sierra Leone"
* $uri#https://hl7.cz/fhir/sid/idcard-SGP "Singapur"
* $uri#https://hl7.cz/fhir/sid/idcard-SXM "Svatý Martin (NL)"
* $uri#https://hl7.cz/fhir/sid/idcard-SVK "Slovensko"
* $uri#https://hl7.cz/fhir/sid/idcard-SVN "Slovinsko"
* $uri#https://hl7.cz/fhir/sid/idcard-SLB "Šalomounovy ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-SOM "Somálsko"
* $uri#https://hl7.cz/fhir/sid/idcard-ZAF "Jižní Afrika"
* $uri#https://hl7.cz/fhir/sid/idcard-SGS "Jižní Georgie a Jižní Sandwichovy ostrovy"
* $uri#https://hl7.cz/fhir/sid/idcard-SSD "Jižní Súdán"
* $uri#https://hl7.cz/fhir/sid/idcard-ESP "Španělsko"
* $uri#https://hl7.cz/fhir/sid/idcard-LKA "Šrí Lanka"
* $uri#https://hl7.cz/fhir/sid/idcard-SDN "Súdán"
* $uri#https://hl7.cz/fhir/sid/idcard-SUR "Surinam"
* $uri#https://hl7.cz/fhir/sid/idcard-SJM "Špicberky a Jan Mayen"
* $uri#https://hl7.cz/fhir/sid/idcard-SWE "Švédsko"
* $uri#https://hl7.cz/fhir/sid/idcard-CHE "Švýcarsko"
* $uri#https://hl7.cz/fhir/sid/idcard-SYR "Sýrie"
* $uri#https://hl7.cz/fhir/sid/idcard-TWN "Sýrie"
* $uri#https://hl7.cz/fhir/sid/idcard-TJK "Tádžikistán"
* $uri#https://hl7.cz/fhir/sid/idcard-TZA "Tádžikistán"
* $uri#https://hl7.cz/fhir/sid/idcard-THA "Thajsko"
* $uri#https://hl7.cz/fhir/sid/idcard-TLS "Východní Timor"
* $uri#https://hl7.cz/fhir/sid/idcard-TGO "Togo"
* $uri#https://hl7.cz/fhir/sid/idcard-TKL "Tokelau"
* $uri#https://hl7.cz/fhir/sid/idcard-TON "Tonga"
* $uri#https://hl7.cz/fhir/sid/idcard-TTO "Trinidad a Tobago"
* $uri#https://hl7.cz/fhir/sid/idcard-TUN "Tunisko"
* $uri#https://hl7.cz/fhir/sid/idcard-TKM "Turkmenistán"
* $uri#https://hl7.cz/fhir/sid/idcard-TCA "Turks a Caicos"
* $uri#https://hl7.cz/fhir/sid/idcard-TUV "Tuvalu"
* $uri#https://hl7.cz/fhir/sid/idcard-TUR "Turecko"
* $uri#https://hl7.cz/fhir/sid/idcard-UGA "Uganda"
* $uri#https://hl7.cz/fhir/sid/idcard-UKR "Ukrajina"
* $uri#https://hl7.cz/fhir/sid/idcard-ARE "Spojené arabské emiráty"
* $uri#https://hl7.cz/fhir/sid/idcard-GBR "Velká Británie"
* $uri#https://hl7.cz/fhir/sid/idcard-UMI "Menší odlehlé ostrovy USA"
* $uri#https://hl7.cz/fhir/sid/idcard-USA "Spojené státy"
* $uri#https://hl7.cz/fhir/sid/idcard-URY "Uruguay"
* $uri#https://hl7.cz/fhir/sid/idcard-UZB "Uzbekistán"
* $uri#https://hl7.cz/fhir/sid/idcard-VUT "Vanuatu"
* $uri#https://hl7.cz/fhir/sid/idcard-VEN "Venezuela"
* $uri#https://hl7.cz/fhir/sid/idcard-VNM "Vietnam"
* $uri#https://hl7.cz/fhir/sid/idcard-VGB "Vietnam"
* $uri#https://hl7.cz/fhir/sid/idcard-VIR "Vietnam"
* $uri#https://hl7.cz/fhir/sid/idcard-WLF "Wallis a Futuna"
* $uri#https://hl7.cz/fhir/sid/idcard-ESH "Západní Sahara"
* $uri#https://hl7.cz/fhir/sid/idcard-YEM "Jemen"
* $uri#https://hl7.cz/fhir/sid/idcard-ZMB "Zambie"
* $uri#https://hl7.cz/fhir/sid/idcard-ZWE "Zimbabwe"
* $uri#https://hl7.cz/fhir/sid/idcard-ALA "Alandy"