ValueSet: OPNSVS
Id: OP-NS
Description: "National identity card's namespaces (CZ)"
* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^title = "Standard namespaces for national identity card"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2023-01-01"
* ^publisher = "HL7 Czech Republic"
* ^language = #cs
* ^jurisdiction = urn:iso:std:iso:3166#CZ "Czechia"
* ^url = "https://hl7.cz/terminology/ValueSet/OP-NS"
* insert SetFmmandStatusRule(1, draft)

* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AFG "OP: Afghánistán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ALB "OP: Albánie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-DZA "OP: Alžírsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ASM "OP: Americká Samoa"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AND "OP: Andorra"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AGO "OP: Angola"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AIA "OP: Anguilla"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ATA "OP: Antarktida"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ATG "OP: Antigua a Barbuda"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ARG "OP: Argentina"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ARM "OP: Arménie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ABW "OP: Aruba"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AUS "OP: Austrálie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AUT "OP: Rakousko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-AZE "OP: Ázerbájdžán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BHS "OP: Bahamy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BHR "OP: Bahrajn"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BGD "OP: Bangladéš"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BRB "OP: Barbados"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BLR "OP: Bělorusko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BEL "OP: Belgie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BLZ "OP: Belize"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BEN "OP: Benin"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BMU "OP: Bermudy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BTN "OP: Bhútán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BOL "OP: Bolívie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BES "OP: Bonaire, Svatý Eustach a Saba"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BIH "OP: Bosna a Hercegovina"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BWA "OP: Botswana"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BVT "OP: Bouvetův ostrov"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BRA "OP: Brazílie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IOT "OP: Britské indickooceánské území"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BRN "OP: Brunej"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BGR "OP: Bulharsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BFA "OP: Burkina Faso"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BDI "OP: Burundi"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CPV "OP: Burundi"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KHM "OP: Kambodža"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CMR "OP: Kamerun"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CAN "OP: Kanada"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CYM "OP: Kajmanské ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CAF "OP: Středoafrická republika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TCD "OP: Čad"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CHL "OP: Chile"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CHN "OP: Čína"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CXR "OP: Vánoční ostrov"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CCK "OP: Kokosové (Keelingovy) ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-COL "OP: Kolumbie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-COM "OP: Komory"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-COD "OP: Konžská republika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-COG "OP: Konžská republika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-COK "OP: Cookovy ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CRI "OP: Kostarika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-HRV "OP: Chorvatsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CUB "OP: Kuba"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CUW "OP: Curaçao"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CYP "OP: Kypr"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CZE "OP: Česko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CIV "OP: Pobřeží slonoviny"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-DNK "OP: Dánsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-DJI "OP: Džibutsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-DMA "OP: Dominika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-DOM "OP: Dominikánská republika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ECU "OP: Ekvádor"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-EGY "OP: Egypt"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SLV "OP: Salvador"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GNQ "OP: Rovníková Guinea"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ERI "OP: Eritrea"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-EST "OP: Estonsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SWZ "OP: Estonsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ETH "OP: Etiopie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-FLK "OP: Falklandy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-FRO "OP: Faerské ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-FJI "OP: Fidži"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-FIN "OP: Finsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-FRA "OP: Francie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GUF "OP: Francouzská Guyana"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PYF "OP: Francouzská Polynésie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ATF "OP: Francouzská jižní a antarktická území"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GAB "OP: Gabon"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GMB "OP: Gambie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GEO "OP: Gruzie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-DEU "OP: Německo"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GHA "OP: Ghana"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GIB "OP: Gibraltar"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GRC "OP: Řecko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GRL "OP: Grónsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GRD "OP: Grenada"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GLP "OP: Guadeloupe"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GUM "OP: Guam"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GTM "OP: Guatemala"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GGY "OP: Guernsey"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GIN "OP: Guinea"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GNB "OP: Guinea-Bissau"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GUY "OP: Guyana"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-HTI "OP: Haiti"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-HMD "OP: Heardův ostrov a MacDonaldovy ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VAT "OP: Vatikán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-HND "OP: Honduras"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-HKG "OP: Hongkong"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-HUN "OP: Maďarsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ISL "OP: Island"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IND "OP: Indie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IDN "OP: Indonésie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IRN "OP: Írán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IRQ "OP: Irák"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IRL "OP: Irsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-IMN "OP: Man"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ISR "OP: Izrael"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ITA "OP: Itálie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-JAM "OP: Jamajka"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-JPN "OP: Japonsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-JEY "OP: Jersey"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-JOR "OP: Jordánsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KAZ "OP: Kazachstán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KEN "OP: Keňa"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KIR "OP: Kiribati"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PRK "OP: Korejská lidově demokratická republika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KOR "OP: Korejská lidově demokratická republika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KWT "OP: Kuvajt"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KGZ "OP: Kyrgyzstán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LAO "OP: Laos"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LVA "OP: Lotyšsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LBN "OP: Libanon"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LSO "OP: Lesotho"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LBR "OP: Libérie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LBY "OP: Libye"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LIE "OP: Lichtenštejnsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LTU "OP: Litva"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LUX "OP: Lucembursko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MAC "OP: Macao"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MDG "OP: Madagaskar"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MWI "OP: Malawi"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MYS "OP: Malajsie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MDV "OP: Maledivy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MLI "OP: Mali"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MLT "OP: Malta"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MHL "OP: Marshallovy ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MTQ "OP: Martinik"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MRT "OP: Mauritánie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MUS "OP: Mauricius"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MYT "OP: Mayotte"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MEX "OP: Mexiko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-FSM "OP: Mikronésie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MDA "OP: Mikronésie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MCO "OP: Monako"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MNG "OP: Mongolsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MNE "OP: Černá Hora"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MSR "OP: Montserrat"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MAR "OP: Maroko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MOZ "OP: Mosambik"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MMR "OP: Myanmar"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NAM "OP: Namibie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NRU "OP: Nauru"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NPL "OP: Nepál"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NLD "OP: Nizozemsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NCL "OP: Nová Kaledonie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NZL "OP: Nový Zéland"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NIC "OP: Nikaragua"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NER "OP: Niger"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NGA "OP: Nigérie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NIU "OP: Niue"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NFK "OP: Norfolk"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MKD "OP: Norfolk"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MNP "OP: Severní Mariany"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-NOR "OP: Norsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-OMN "OP: Omán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PAK "OP: Pákistán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PLW "OP: Palau"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PSE "OP: Palestina"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PAN "OP: Panama"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PNG "OP: Papua Nová Guinea"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PRY "OP: Paraguay"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PER "OP: Peru"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PHL "OP: Filipíny"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PCN "OP: Pitcairn"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-POL "OP: Polsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PRT "OP: Portugalsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-PRI "OP: Portoriko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-QAT "OP: Katar"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ROU "OP: Rumunsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-RUS "OP: Rusko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-RWA "OP: Rwanda"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-REU "OP: Réunion"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-BLM "OP: Svatý Bartoloměj"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SHN "OP: Svatá Helena"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-KNA "OP: Svatý Kryštof a Nevis"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LCA "OP: Svatá Lucie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-MAF "OP: Svatý Martin (FR)"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SPM "OP: Saint Pierre a Miquelon"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VCT "OP: Svatý Vincenc a Grenadiny"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-WSM "OP: Samoa"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SMR "OP: San Marino"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-STP "OP: Svatý Tomáš a Princův ostrov"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SAU "OP: Saúdská Arábie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SEN "OP: Senegal"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SRB "OP: Srbsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SYC "OP: Seychely"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SLE "OP: Sierra Leone"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SGP "OP: Singapur"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SXM "OP: Svatý Martin (NL)"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SVK "OP: Slovensko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SVN "OP: Slovinsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SLB "OP: Šalomounovy ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SOM "OP: Somálsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ZAF "OP: Jižní Afrika"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SGS "OP: Jižní Georgie a Jižní Sandwichovy ostrovy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SSD "OP: Jižní Súdán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ESP "OP: Španělsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-LKA "OP: Šrí Lanka"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SDN "OP: Súdán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SUR "OP: Surinam"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SJM "OP: Špicberky a Jan Mayen"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SWE "OP: Švédsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-CHE "OP: Švýcarsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-SYR "OP: Sýrie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TWN "OP: Sýrie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TJK "OP: Tádžikistán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TZA "OP: Tádžikistán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-THA "OP: Thajsko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TLS "OP: Východní Timor"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TGO "OP: Togo"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TKL "OP: Tokelau"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TON "OP: Tonga"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TTO "OP: Trinidad a Tobago"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TUN "OP: Tunisko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TKM "OP: Turkmenistán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TCA "OP: Turks a Caicos"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TUV "OP: Tuvalu"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-TUR "OP: Turecko"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-UGA "OP: Uganda"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-UKR "OP: Ukrajina"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ARE "OP: Spojené arabské emiráty"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-GBR "OP: Velká Británie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-UMI "OP: Menší odlehlé ostrovy USA"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-USA "OP: Spojené státy"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-URY "OP: Uruguay"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-UZB "OP: Uzbekistán"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VUT "OP: Vanuatu"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VEN "OP: Venezuela"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VNM "OP: Vietnam"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VGB "OP: Vietnam"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-VIR "OP: Vietnam"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-WLF "OP: Wallis a Futuna"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ESH "OP: Západní Sahara"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-YEM "OP: Jemen"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ZMB "OP: Zambie"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ZWE "OP: Zimbabwe"
* $uri#https://hl7.cz/NamingSystem/IdCardNumNS-ALA "OP: Alandy"
