ValueSet: PassportNSVS
Id: passport-NS-VS
Title: "Passport namespaces (CZ)"
Description: "Číselník jmenných prostorů pro pasy. (Passport namespaces.)"
//* ^meta.profile = "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
* ^title = "Standard namespaces for passports"
* ^url = "https://ncez.mzcr.cz/fhir/ValueSet/PassportNS-vs"
* ^version = "1.0.0"
* ^status = #draft
* ^experimental = false
* ^date = "2023-01-01"
* ^publisher = "HL7 Czech Republic"
* ^language = #cs
* ^jurisdiction = urn:iso:std:iso:3166#CZ "Czechia"
* insert SetFmmandStatusRule(1, draft)

* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AFG "Pas: Afghánistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ALB "Pas: Albánie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DZA "Pas: Alžírsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ASM "Pas: Americká Samoa"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AND "Pas: Andorra"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AGO "Pas: Angola"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AIA "Pas: Anguilla"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ATA "Pas: Antarktida"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ATG "Pas: Antigua a Barbuda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ARG "Pas: Argentina"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ARM "Pas: Arménie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ABW "Pas: Aruba"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AUS "Pas: Austrálie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AUT "Pas: Rakousko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AZE "Pas: Ázerbájdžán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BHS "Pas: Bahamy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BHR "Pas: Bahrajn"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BGD "Pas: Bangladéš"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BRB "Pas: Barbados"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BLR "Pas: Bělorusko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BEL "Pas: Belgie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BLZ "Pas: Belize"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BEN "Pas: Benin"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BMU "Pas: Bermudy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BTN "Pas: Bhútán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BOL "Pas: Bolívie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BES "Pas: Bonaire, Svatý Eustach a Saba"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BIH "Pas: Bosna a Hercegovina"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BWA "Pas: Botswana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BVT "Pas: Bouvetův ostrov"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BRA "Pas: Brazílie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IOT "Pas: Britské indickooceánské území"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BRN "Pas: Brunej"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BGR "Pas: Bulharsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BFA "Pas: Burkina Faso"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BDI "Pas: Burundi"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CPV "Pas: Burundi"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KHM "Pas: Kambodža"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CMR "Pas: Kamerun"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CAN "Pas: Kanada"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CYM "Pas: Kajmanské ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CAF "Pas: Středoafrická republika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TCD "Pas: Čad"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CHL "Pas: Chile"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CHN "Pas: Čína"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CXR "Pas: Vánoční ostrov"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CCK "Pas: Kokosové (Keelingovy) ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COL "Pas: Kolumbie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COM "Pas: Komory"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COD "Pas: Konžská republika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COG "Pas: Konžská republika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COK "Pas: Cookovy ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CRI "Pas: Kostarika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HRV "Pas: Chorvatsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CUB "Pas: Kuba"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CUW "Pas: Curaçao"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CYP "Pas: Kypr"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CZE "Pas: Česko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CIV "Pas: Pobřeží slonoviny"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DNK "Pas: Dánsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DJI "Pas: Džibutsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DMA "Pas: Dominika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DOM "Pas: Dominikánská republika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ECU "Pas: Ekvádor"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-EGY "Pas: Egypt"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SLV "Pas: Salvador"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GNQ "Pas: Rovníková Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ERI "Pas: Eritrea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-EST "Pas: Estonsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SWZ "Pas: Estonsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ETH "Pas: Etiopie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FLK "Pas: Falklandy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FRO "Pas: Faerské ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FJI "Pas: Fidži"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FIN "Pas: Finsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FRA "Pas: Francie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GUF "Pas: Francouzská Guyana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PYF "Pas: Francouzská Polynésie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ATF "Pas: Francouzská jižní a antarktická území"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GAB "Pas: Gabon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GMB "Pas: Gambie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GEO "Pas: Gruzie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DEU "Pas: Německo"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GHA "Pas: Ghana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GIB "Pas: Gibraltar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GRC "Pas: Řecko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GRL "Pas: Grónsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GRD "Pas: Grenada"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GLP "Pas: Guadeloupe"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GUM "Pas: Guam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GTM "Pas: Guatemala"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GGY "Pas: Guernsey"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GIN "Pas: Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GNB "Pas: Guinea-Bissau"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GUY "Pas: Guyana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HTI "Pas: Haiti"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HMD "Pas: Heardův ostrov a MacDonaldovy ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VAT "Pas: Vatikán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HND "Pas: Honduras"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HKG "Pas: Hongkong"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HUN "Pas: Maďarsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ISL "Pas: Island"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IND "Pas: Indie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IDN "Pas: Indonésie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IRN "Pas: Írán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IRQ "Pas: Irák"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IRL "Pas: Irsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IMN "Pas: Man"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ISR "Pas: Izrael"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ITA "Pas: Itálie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JAM "Pas: Jamajka"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JPN "Pas: Japonsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JEY "Pas: Jersey"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JOR "Pas: Jordánsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KAZ "Pas: Kazachstán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KEN "Pas: Keňa"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KIR "Pas: Kiribati"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRK "Pas: Korejská lidově demokratická republika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KOR "Pas: Korejská lidově demokratická republika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KWT "Pas: Kuvajt"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KGZ "Pas: Kyrgyzstán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LAO "Pas: Laos"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LVA "Pas: Lotyšsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LBN "Pas: Libanon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LSO "Pas: Lesotho"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LBR "Pas: Libérie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LBY "Pas: Libye"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LIE "Pas: Lichtenštejnsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LTU "Pas: Litva"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LUX "Pas: Lucembursko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MAC "Pas: Macao"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MDG "Pas: Madagaskar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MWI "Pas: Malawi"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MYS "Pas: Malajsie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MDV "Pas: Maledivy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MLI "Pas: Mali"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MLT "Pas: Malta"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MHL "Pas: Marshallovy ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MTQ "Pas: Martinik"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MRT "Pas: Mauritánie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MUS "Pas: Mauricius"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MYT "Pas: Mayotte"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MEX "Pas: Mexiko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FSM "Pas: Mikronésie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MDA "Pas: Mikronésie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MCO "Pas: Monako"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MNG "Pas: Mongolsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MNE "Pas: Černá Hora"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MSR "Pas: Montserrat"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MAR "Pas: Maroko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MOZ "Pas: Mosambik"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MMR "Pas: Myanmar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NAM "Pas: Namibie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NRU "Pas: Nauru"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NPL "Pas: Nepál"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NLD "Pas: Nizozemsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NCL "Pas: Nová Kaledonie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NZL "Pas: Nový Zéland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NIC "Pas: Nikaragua"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NER "Pas: Niger"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NGA "Pas: Nigérie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NIU "Pas: Niue"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NFK "Pas: Norfolk"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MKD "Pas: Norfolk"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MNP "Pas: Severní Mariany"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NOR "Pas: Norsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-OMN "Pas: Omán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PAK "Pas: Pákistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PLW "Pas: Palau"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PSE "Pas: Palestina"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PAN "Pas: Panama"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PNG "Pas: Papua Nová Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRY "Pas: Paraguay"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PER "Pas: Peru"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PHL "Pas: Filipíny"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PCN "Pas: Pitcairn"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-POL "Pas: Polsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRT "Pas: Portugalsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRI "Pas: Portoriko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-QAT "Pas: Katar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ROU "Pas: Rumunsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-RUS "Pas: Rusko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-RWA "Pas: Rwanda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-REU "Pas: Réunion"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BLM "Pas: Svatý Bartoloměj"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SHN "Pas: Svatá Helena"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KNA "Pas: Svatý Kryštof a Nevis"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LCA "Pas: Svatá Lucie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MAF "Pas: Svatý Martin (FR)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SPM "Pas: Saint Pierre a Miquelon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VCT "Pas: Svatý Vincenc a Grenadiny"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-WSM "Pas: Samoa"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SMR "Pas: San Marino"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-STP "Pas: Svatý Tomáš a Princův ostrov"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SAU "Pas: Saúdská Arábie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SEN "Pas: Senegal"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SRB "Pas: Srbsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SYC "Pas: Seychely"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SLE "Pas: Sierra Leone"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SGP "Pas: Singapur"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SXM "Pas: Svatý Martin (NL)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SVK "Pas: Slovensko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SVN "Pas: Slovinsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SLB "Pas: Šalomounovy ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SOM "Pas: Somálsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ZAF "Pas: Jižní Afrika"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SGS "Pas: Jižní Georgie a Jižní Sandwichovy ostrovy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SSD "Pas: Jižní Súdán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ESP "Pas: Španělsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LKA "Pas: Šrí Lanka"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SDN "Pas: Súdán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SUR "Pas: Surinam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SJM "Pas: Špicberky a Jan Mayen"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SWE "Pas: Švédsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CHE "Pas: Švýcarsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SYR "Pas: Sýrie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TWN "Pas: Sýrie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TJK "Pas: Tádžikistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TZA "Pas: Tádžikistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-THA "Pas: Thajsko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TLS "Pas: Východní Timor"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TGO "Pas: Togo"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TKL "Pas: Tokelau"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TON "Pas: Tonga"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TTO "Pas: Trinidad a Tobago"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TUN "Pas: Tunisko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TKM "Pas: Turkmenistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TCA "Pas: Turks a Caicos"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TUV "Pas: Tuvalu"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TUR "Pas: Turecko"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UGA "Pas: Uganda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UKR "Pas: Ukrajina"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ARE "Pas: Spojené arabské emiráty"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GBR "Pas: Velká Británie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UMI "Pas: Menší odlehlé ostrovy USA"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-USA "Pas: Spojené státy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-URY "Pas: Uruguay"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UZB "Pas: Uzbekistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VUT "Pas: Vanuatu"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VEN "Pas: Venezuela"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VNM "Pas: Vietnam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VGB "Pas: Vietnam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VIR "Pas: Vietnam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-WLF "Pas: Wallis a Futuna"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ESH "Pas: Západní Sahara"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-YEM "Pas: Jemen"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ZMB "Pas: Zambie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ZWE "Pas: Zimbabwe"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ALA "Pas: Alandy"

/*
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AFG "Pas: Afghánistán"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ALB "Pas: Albánie"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DZA "Pas: Algeria"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ASM "Pas: American Samoa"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AND "Pas: Andorra"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AGO "Pas: Angola"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AIA "Pas: Anguilla"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ATA "Pas: Antarctica"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ATG "Pas: Antigua and Barbuda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ARG "Pas: Argentina"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ARM "Pas: Armenia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ABW "Pas: Aruba"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AUS "Pas: Australia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AUT "Pas: Austria"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-AZE "Pas: Azerbaijan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BHS "Pas: Bahamas (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BHR "Pas: Bahrain"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BGD "Pas: Bangladesh"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BRB "Pas: Barbados"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BLR "Pas: Belarus"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BEL "Pas: Belgium"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BLZ "Pas: Belize"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BEN "Pas: Benin"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BMU "Pas: Bermuda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BTN "Pas: Bhutan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BOL "Pas: Bolivia (Plurinational State of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BES "Pas: Bonaire, Sint Eustatius and Saba"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BIH "Pas: Bosnia and Herzegovina"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BWA "Pas: Botswana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BVT "Pas: Bouvet Island"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BRA "Pas: Brazil"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IOT "Pas: British Indian Ocean Territory (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BRN "Pas: Brunei Darussalam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BGR "Pas: Bulgaria"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BFA "Pas: Burkina Faso"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BDI "Pas: Burundi"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CPV "Pas: Cabo Verde"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KHM "Pas: Cambodia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CMR "Pas: Cameroon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CAN "Pas: Canada"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CYM "Pas: Cayman Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CAF "Pas: Central African Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TCD "Pas: Chad"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CHL "Pas: Chile"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CHN "Pas: China"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CXR "Pas: Christmas Island"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CCK "Pas: Cocos (Keeling) Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COL "Pas: Colombia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COM "Pas: Comoros (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COD "Pas: Congo (the Democratic Republic of the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COG "Pas: Congo (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-COK "Pas: Cook Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CRI "Pas: Costa Rica"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HRV "Pas: Croatia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CUB "Pas: Cuba"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CUW "Pas: Curaçao"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CYP "Pas: Cyprus"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CZE "Pas: Czechia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CIV "Pas: Côte d'Ivoire"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DNK "Pas: Denmark"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DJI "Pas: Djibouti"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DMA "Pas: Dominica"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DOM "Pas: Dominican Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ECU "Pas: Ecuador"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-EGY "Pas: Egypt"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SLV "Pas: El Salvador"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GNQ "Pas: Equatorial Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ERI "Pas: Eritrea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-EST "Pas: Estonia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SWZ "Pas: Eswatini"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ETH "Pas: Ethiopia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FLK "Pas: Falkland Islands (the) [Malvinas]"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FRO "Pas: Faroe Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FJI "Pas: Fiji"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FIN "Pas: Finland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FRA "Pas: France"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GUF "Pas: French Guiana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PYF "Pas: French Polynesia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ATF "Pas: French Southern Territories (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GAB "Pas: Gabon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GMB "Pas: Gambia (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GEO "Pas: Georgia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-DEU "Pas: Germany"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GHA "Pas: Ghana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GIB "Pas: Gibraltar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GRC "Pas: Greece"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GRL "Pas: Greenland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GRD "Pas: Grenada"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GLP "Pas: Guadeloupe"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GUM "Pas: Guam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GTM "Pas: Guatemala"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GGY "Pas: Guernsey"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GIN "Pas: Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GNB "Pas: Guinea-Bissau"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GUY "Pas: Guyana"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HTI "Pas: Haiti"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HMD "Pas: Heard Island and McDonald Islands"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VAT "Pas: Holy See (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HND "Pas: Honduras"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HKG "Pas: Hong Kong"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-HUN "Pas: Hungary"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ISL "Pas: Iceland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IND "Pas: India"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IDN "Pas: Indonesia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IRN "Pas: Iran (Islamic Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IRQ "Pas: Iraq"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IRL "Pas: Ireland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-IMN "Pas: Isle of Man"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ISR "Pas: Israel"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ITA "Pas: Italy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JAM "Pas: Jamaica"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JPN "Pas: Japan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JEY "Pas: Jersey"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-JOR "Pas: Jordan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KAZ "Pas: Kazakhstan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KEN "Pas: Kenya"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KIR "Pas: Kiribati"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRK "Pas: Korea (the Democratic People's Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KOR "Pas: Korea (the Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KWT "Pas: Kuwait"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KGZ "Pas: Kyrgyzstan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LAO "Pas: Lao People's Democratic Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LVA "Pas: Latvia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LBN "Pas: Lebanon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LSO "Pas: Lesotho"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LBR "Pas: Liberia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LBY "Pas: Libya"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LIE "Pas: Liechtenstein"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LTU "Pas: Lithuania"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LUX "Pas: Luxembourg"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MAC "Pas: Macao"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MDG "Pas: Madagascar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MWI "Pas: Malawi"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MYS "Pas: Malaysia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MDV "Pas: Maldives"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MLI "Pas: Mali"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MLT "Pas: Malta"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MHL "Pas: Marshall Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MTQ "Pas: Martinique"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MRT "Pas: Mauritania"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MUS "Pas: Mauritius"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MYT "Pas: Mayotte"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MEX "Pas: Mexico"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-FSM "Pas: Micronesia (Federated States of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MDA "Pas: Moldova (the Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MCO "Pas: Monaco"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MNG "Pas: Mongolia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MNE "Pas: Montenegro"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MSR "Pas: Montserrat"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MAR "Pas: Morocco"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MOZ "Pas: Mozambique"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MMR "Pas: Myanmar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NAM "Pas: Namibia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NRU "Pas: Nauru"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NPL "Pas: Nepal"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NLD "Pas: Netherlands (Kingdom of the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NCL "Pas: New Caledonia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NZL "Pas: New Zealand"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NIC "Pas: Nicaragua"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NER "Pas: Niger (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NGA "Pas: Nigeria"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NIU "Pas: Niue"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NFK "Pas: Norfolk Island"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MKD "Pas: North Macedonia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MNP "Pas: Northern Mariana Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-NOR "Pas: Norway"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-OMN "Pas: Oman"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PAK "Pas: Pakistan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PLW "Pas: Palau"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PSE "Pas: Palestine, State of"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PAN "Pas: Panama"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PNG "Pas: Papua New Guinea"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRY "Pas: Paraguay"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PER "Pas: Peru"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PHL "Pas: Philippines (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PCN "Pas: Pitcairn"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-POL "Pas: Poland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRT "Pas: Portugal"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-PRI "Pas: Puerto Rico"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-QAT "Pas: Qatar"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ROU "Pas: Romania"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-RUS "Pas: Russian Federation (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-RWA "Pas: Rwanda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-REU "Pas: Réunion"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-BLM "Pas: Saint Barthélemy"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SHN "Pas: Saint Helena, Ascension and Tristan da Cunha"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-KNA "Pas: Saint Kitts and Nevis"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LCA "Pas: Saint Lucia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-MAF "Pas: Saint Martin (French part)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SPM "Pas: Saint Pierre and Miquelon"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VCT "Pas: Saint Vincent and the Grenadines"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-WSM "Pas: Samoa"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SMR "Pas: San Marino"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-STP "Pas: Sao Tome and Principe"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SAU "Pas: Saudi Arabia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SEN "Pas: Senegal"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SRB "Pas: Serbia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SYC "Pas: Seychelles"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SLE "Pas: Sierra Leone"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SGP "Pas: Singapore"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SXM "Pas: Sint Maarten (Dutch part)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SVK "Pas: Slovakia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SVN "Pas: Slovenia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SLB "Pas: Solomon Islands"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SOM "Pas: Somalia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ZAF "Pas: South Africa"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SGS "Pas: South Georgia and the South Sandwich Islands"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SSD "Pas: South Sudan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ESP "Pas: Spain"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-LKA "Pas: Sri Lanka"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SDN "Pas: Sudan (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SUR "Pas: Suriname"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SJM "Pas: Svalbard and Jan Mayen"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SWE "Pas: Sweden"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-CHE "Pas: Switzerland"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-SYR "Pas: Syrian Arab Republic (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TWN "Pas: Taiwan (Province of China)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TJK "Pas: Tajikistan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TZA "Pas: Tanzania, the United Republic of"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-THA "Pas: Thailand"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TLS "Pas: Timor-Leste"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TGO "Pas: Togo"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TKL "Pas: Tokelau"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TON "Pas: Tonga"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TTO "Pas: Trinidad and Tobago"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TUN "Pas: Tunisia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TKM "Pas: Turkmenistan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TCA "Pas: Turks and Caicos Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TUV "Pas: Tuvalu"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-TUR "Pas: Türkiye"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UGA "Pas: Uganda"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UKR "Pas: Ukraine"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ARE "Pas: United Arab Emirates (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-GBR "Pas: United Kingdom of Great Britain and Northern Ireland (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UMI "Pas: United States Minor Outlying Islands (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-USA "Pas: United States of America (the)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-URY "Pas: Uruguay"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-UZB "Pas: Uzbekistan"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VUT "Pas: Vanuatu"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VEN "Pas: Venezuela (Bolivarian Republic of)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VNM "Pas: Viet Nam"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VGB "Pas: Virgin Islands (British)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-VIR "Pas: Virgin Islands (U.S.)"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-WLF "Pas: Wallis and Futuna"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ESH "Pas: Western Sahara*"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-YEM "Pas: Yemen"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ZMB "Pas: Zambia"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ZWE "Pas: Zimbabwe"
* $uri#http://terminology.hl7.org/NamingSystem/passportNumNS-ALA "Pas: Åland Islands"
*/