ValueSet: PassportUri
Id: passport-uri
Title: "Passport URIs"
Description: "A country specific URI for passport numbers"
* ^url = "https://hl7.cz/terminology/ValueSet/passport-uri"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2026-01-01"
* ^publisher = "HL7 Czech Republic"
* ^language = #cs
* ^jurisdiction = urn:iso:std:iso:3166#CZ "Czechia"
* insert SetFmmandStatusRule(2, trial-use)

* $uri#http://hl7.org/fhir/sid/passport-AFG "Afghánistán"
* $uri#http://hl7.org/fhir/sid/passport-ALB "Albánie"
* $uri#http://hl7.org/fhir/sid/passport-DZA "Alžírsko"
* $uri#http://hl7.org/fhir/sid/passport-ASM "Americká Samoa"
* $uri#http://hl7.org/fhir/sid/passport-AND "Andorra"
* $uri#http://hl7.org/fhir/sid/passport-AGO "Angola"
* $uri#http://hl7.org/fhir/sid/passport-AIA "Anguilla"
* $uri#http://hl7.org/fhir/sid/passport-ATA "Antarktida"
* $uri#http://hl7.org/fhir/sid/passport-ATG "Antigua a Barbuda"
* $uri#http://hl7.org/fhir/sid/passport-ARG "Argentina"
* $uri#http://hl7.org/fhir/sid/passport-ARM "Arménie"
* $uri#http://hl7.org/fhir/sid/passport-ABW "Aruba"
* $uri#http://hl7.org/fhir/sid/passport-AUS "Austrálie"
* $uri#http://hl7.org/fhir/sid/passport-AUT "Rakousko"
* $uri#http://hl7.org/fhir/sid/passport-AZE "Ázerbájdžán"
* $uri#http://hl7.org/fhir/sid/passport-BHS "Bahamy"
* $uri#http://hl7.org/fhir/sid/passport-BHR "Bahrajn"
* $uri#http://hl7.org/fhir/sid/passport-BGD "Bangladéš"
* $uri#http://hl7.org/fhir/sid/passport-BRB "Barbados"
* $uri#http://hl7.org/fhir/sid/passport-BLR "Bělorusko"
* $uri#http://hl7.org/fhir/sid/passport-BEL "Belgie"
* $uri#http://hl7.org/fhir/sid/passport-BLZ "Belize"
* $uri#http://hl7.org/fhir/sid/passport-BEN "Benin"
* $uri#http://hl7.org/fhir/sid/passport-BMU "Bermudy"
* $uri#http://hl7.org/fhir/sid/passport-BTN "Bhútán"
* $uri#http://hl7.org/fhir/sid/passport-BOL "Bolívie"
* $uri#http://hl7.org/fhir/sid/passport-BES "Bonaire, Svatý Eustach a Saba"
* $uri#http://hl7.org/fhir/sid/passport-BIH "Bosna a Hercegovina"
* $uri#http://hl7.org/fhir/sid/passport-BWA "Botswana"
* $uri#http://hl7.org/fhir/sid/passport-BVT "Bouvetův ostrov"
* $uri#http://hl7.org/fhir/sid/passport-BRA "Brazílie"
* $uri#http://hl7.org/fhir/sid/passport-IOT "Britské indickooceánské území"
* $uri#http://hl7.org/fhir/sid/passport-BRN "Brunej"
* $uri#http://hl7.org/fhir/sid/passport-BGR "Bulharsko"
* $uri#http://hl7.org/fhir/sid/passport-BFA "Burkina Faso"
* $uri#http://hl7.org/fhir/sid/passport-BDI "Burundi"
* $uri#http://hl7.org/fhir/sid/passport-CPV "Burundi"
* $uri#http://hl7.org/fhir/sid/passport-KHM "Kambodža"
* $uri#http://hl7.org/fhir/sid/passport-CMR "Kamerun"
* $uri#http://hl7.org/fhir/sid/passport-CAN "Kanada"
* $uri#http://hl7.org/fhir/sid/passport-CYM "Kajmanské ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-CAF "Středoafrická republika"
* $uri#http://hl7.org/fhir/sid/passport-TCD "Čad"
* $uri#http://hl7.org/fhir/sid/passport-CHL "Chile"
* $uri#http://hl7.org/fhir/sid/passport-CHN "Čína"
* $uri#http://hl7.org/fhir/sid/passport-CXR "Vánoční ostrov"
* $uri#http://hl7.org/fhir/sid/passport-CCK "Kokosové (Keelingovy) ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-COL "Kolumbie"
* $uri#http://hl7.org/fhir/sid/passport-COM "Komory"
* $uri#http://hl7.org/fhir/sid/passport-COD "Konžská republika"
* $uri#http://hl7.org/fhir/sid/passport-COG "Konžská republika"
* $uri#http://hl7.org/fhir/sid/passport-COK "Cookovy ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-CRI "Kostarika"
* $uri#http://hl7.org/fhir/sid/passport-HRV "Chorvatsko"
* $uri#http://hl7.org/fhir/sid/passport-CUB "Kuba"
* $uri#http://hl7.org/fhir/sid/passport-CUW "Curaçao"
* $uri#http://hl7.org/fhir/sid/passport-CYP "Kypr"
* $uri#http://hl7.org/fhir/sid/passport-CZE "Česko"
* $uri#http://hl7.org/fhir/sid/passport-CIV "Pobřeží slonoviny"
* $uri#http://hl7.org/fhir/sid/passport-DNK "Dánsko"
* $uri#http://hl7.org/fhir/sid/passport-DJI "Džibutsko"
* $uri#http://hl7.org/fhir/sid/passport-DMA "Dominika"
* $uri#http://hl7.org/fhir/sid/passport-DOM "Dominikánská republika"
* $uri#http://hl7.org/fhir/sid/passport-ECU "Ekvádor"
* $uri#http://hl7.org/fhir/sid/passport-EGY "Egypt"
* $uri#http://hl7.org/fhir/sid/passport-SLV "Salvador"
* $uri#http://hl7.org/fhir/sid/passport-GNQ "Rovníková Guinea"
* $uri#http://hl7.org/fhir/sid/passport-ERI "Eritrea"
* $uri#http://hl7.org/fhir/sid/passport-EST "Estonsko"
* $uri#http://hl7.org/fhir/sid/passport-SWZ "Estonsko"
* $uri#http://hl7.org/fhir/sid/passport-ETH "Etiopie"
* $uri#http://hl7.org/fhir/sid/passport-FLK "Falklandy"
* $uri#http://hl7.org/fhir/sid/passport-FRO "Faerské ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-FJI "Fidži"
* $uri#http://hl7.org/fhir/sid/passport-FIN "Finsko"
* $uri#http://hl7.org/fhir/sid/passport-FRA "Francie"
* $uri#http://hl7.org/fhir/sid/passport-GUF "Francouzská Guyana"
* $uri#http://hl7.org/fhir/sid/passport-PYF "Francouzská Polynésie"
* $uri#http://hl7.org/fhir/sid/passport-ATF "Francouzská jižní a antarktická území"
* $uri#http://hl7.org/fhir/sid/passport-GAB "Gabon"
* $uri#http://hl7.org/fhir/sid/passport-GMB "Gambie"
* $uri#http://hl7.org/fhir/sid/passport-GEO "Gruzie"
* $uri#http://hl7.org/fhir/sid/passport-DEU "Německo"
* $uri#http://hl7.org/fhir/sid/passport-GHA "Ghana"
* $uri#http://hl7.org/fhir/sid/passport-GIB "Gibraltar"
* $uri#http://hl7.org/fhir/sid/passport-GRC "Řecko"
* $uri#http://hl7.org/fhir/sid/passport-GRL "Grónsko"
* $uri#http://hl7.org/fhir/sid/passport-GRD "Grenada"
* $uri#http://hl7.org/fhir/sid/passport-GLP "Guadeloupe"
* $uri#http://hl7.org/fhir/sid/passport-GUM "Guam"
* $uri#http://hl7.org/fhir/sid/passport-GTM "Guatemala"
* $uri#http://hl7.org/fhir/sid/passport-GGY "Guernsey"
* $uri#http://hl7.org/fhir/sid/passport-GIN "Guinea"
* $uri#http://hl7.org/fhir/sid/passport-GNB "Guinea-Bissau"
* $uri#http://hl7.org/fhir/sid/passport-GUY "Guyana"
* $uri#http://hl7.org/fhir/sid/passport-HTI "Haiti"
* $uri#http://hl7.org/fhir/sid/passport-HMD "Heardův ostrov a MacDonaldovy ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-VAT "Vatikán"
* $uri#http://hl7.org/fhir/sid/passport-HND "Honduras"
* $uri#http://hl7.org/fhir/sid/passport-HKG "Hongkong"
* $uri#http://hl7.org/fhir/sid/passport-HUN "Maďarsko"
* $uri#http://hl7.org/fhir/sid/passport-ISL "Island"
* $uri#http://hl7.org/fhir/sid/passport-IND "Indie"
* $uri#http://hl7.org/fhir/sid/passport-IDN "Indonésie"
* $uri#http://hl7.org/fhir/sid/passport-IRN "Írán"
* $uri#http://hl7.org/fhir/sid/passport-IRQ "Irák"
* $uri#http://hl7.org/fhir/sid/passport-IRL "Irsko"
* $uri#http://hl7.org/fhir/sid/passport-IMN "Man"
* $uri#http://hl7.org/fhir/sid/passport-ISR "Izrael"
* $uri#http://hl7.org/fhir/sid/passport-ITA "Itálie"
* $uri#http://hl7.org/fhir/sid/passport-JAM "Jamajka"
* $uri#http://hl7.org/fhir/sid/passport-JPN "Japonsko"
* $uri#http://hl7.org/fhir/sid/passport-JEY "Jersey"
* $uri#http://hl7.org/fhir/sid/passport-JOR "Jordánsko"
* $uri#http://hl7.org/fhir/sid/passport-KAZ "Kazachstán"
* $uri#http://hl7.org/fhir/sid/passport-KEN "Keňa"
* $uri#http://hl7.org/fhir/sid/passport-KIR "Kiribati"
* $uri#http://hl7.org/fhir/sid/passport-PRK "Korejská lidově demokratická republika"
* $uri#http://hl7.org/fhir/sid/passport-KOR "Korejská lidově demokratická republika"
* $uri#http://hl7.org/fhir/sid/passport-KWT "Kuvajt"
* $uri#http://hl7.org/fhir/sid/passport-KGZ "Kyrgyzstán"
* $uri#http://hl7.org/fhir/sid/passport-LAO "Laos"
* $uri#http://hl7.org/fhir/sid/passport-LVA "Lotyšsko"
* $uri#http://hl7.org/fhir/sid/passport-LBN "Libanon"
* $uri#http://hl7.org/fhir/sid/passport-LSO "Lesotho"
* $uri#http://hl7.org/fhir/sid/passport-LBR "Libérie"
* $uri#http://hl7.org/fhir/sid/passport-LBY "Libye"
* $uri#http://hl7.org/fhir/sid/passport-LIE "Lichtenštejnsko"
* $uri#http://hl7.org/fhir/sid/passport-LTU "Litva"
* $uri#http://hl7.org/fhir/sid/passport-LUX "Lucembursko"
* $uri#http://hl7.org/fhir/sid/passport-MAC "Macao"
* $uri#http://hl7.org/fhir/sid/passport-MDG "Madagaskar"
* $uri#http://hl7.org/fhir/sid/passport-MWI "Malawi"
* $uri#http://hl7.org/fhir/sid/passport-MYS "Malajsie"
* $uri#http://hl7.org/fhir/sid/passport-MDV "Maledivy"
* $uri#http://hl7.org/fhir/sid/passport-MLI "Mali"
* $uri#http://hl7.org/fhir/sid/passport-MLT "Malta"
* $uri#http://hl7.org/fhir/sid/passport-MHL "Marshallovy ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-MTQ "Martinik"
* $uri#http://hl7.org/fhir/sid/passport-MRT "Mauritánie"
* $uri#http://hl7.org/fhir/sid/passport-MUS "Mauricius"
* $uri#http://hl7.org/fhir/sid/passport-MYT "Mayotte"
* $uri#http://hl7.org/fhir/sid/passport-MEX "Mexiko"
* $uri#http://hl7.org/fhir/sid/passport-FSM "Mikronésie"
* $uri#http://hl7.org/fhir/sid/passport-MDA "Mikronésie"
* $uri#http://hl7.org/fhir/sid/passport-MCO "Monako"
* $uri#http://hl7.org/fhir/sid/passport-MNG "Mongolsko"
* $uri#http://hl7.org/fhir/sid/passport-MNE "Černá Hora"
* $uri#http://hl7.org/fhir/sid/passport-MSR "Montserrat"
* $uri#http://hl7.org/fhir/sid/passport-MAR "Maroko"
* $uri#http://hl7.org/fhir/sid/passport-MOZ "Mosambik"
* $uri#http://hl7.org/fhir/sid/passport-MMR "Myanmar"
* $uri#http://hl7.org/fhir/sid/passport-NAM "Namibie"
* $uri#http://hl7.org/fhir/sid/passport-NRU "Nauru"
* $uri#http://hl7.org/fhir/sid/passport-NPL "Nepál"
* $uri#http://hl7.org/fhir/sid/passport-NLD "Nizozemsko"
* $uri#http://hl7.org/fhir/sid/passport-NCL "Nová Kaledonie"
* $uri#http://hl7.org/fhir/sid/passport-NZL "Nový Zéland"
* $uri#http://hl7.org/fhir/sid/passport-NIC "Nikaragua"
* $uri#http://hl7.org/fhir/sid/passport-NER "Niger"
* $uri#http://hl7.org/fhir/sid/passport-NGA "Nigérie"
* $uri#http://hl7.org/fhir/sid/passport-NIU "Niue"
* $uri#http://hl7.org/fhir/sid/passport-NFK "Norfolk"
* $uri#http://hl7.org/fhir/sid/passport-MKD "Norfolk"
* $uri#http://hl7.org/fhir/sid/passport-MNP "Severní Mariany"
* $uri#http://hl7.org/fhir/sid/passport-NOR "Norsko"
* $uri#http://hl7.org/fhir/sid/passport-OMN "Omán"
* $uri#http://hl7.org/fhir/sid/passport-PAK "Pákistán"
* $uri#http://hl7.org/fhir/sid/passport-PLW "Palau"
* $uri#http://hl7.org/fhir/sid/passport-PSE "Palestina"
* $uri#http://hl7.org/fhir/sid/passport-PAN "Panama"
* $uri#http://hl7.org/fhir/sid/passport-PNG "Papua Nová Guinea"
* $uri#http://hl7.org/fhir/sid/passport-PRY "Paraguay"
* $uri#http://hl7.org/fhir/sid/passport-PER "Peru"
* $uri#http://hl7.org/fhir/sid/passport-PHL "Filipíny"
* $uri#http://hl7.org/fhir/sid/passport-PCN "Pitcairn"
* $uri#http://hl7.org/fhir/sid/passport-POL "Polsko"
* $uri#http://hl7.org/fhir/sid/passport-PRT "Portugalsko"
* $uri#http://hl7.org/fhir/sid/passport-PRI "Portoriko"
* $uri#http://hl7.org/fhir/sid/passport-QAT "Katar"
* $uri#http://hl7.org/fhir/sid/passport-ROU "Rumunsko"
* $uri#http://hl7.org/fhir/sid/passport-RUS "Rusko"
* $uri#http://hl7.org/fhir/sid/passport-RWA "Rwanda"
* $uri#http://hl7.org/fhir/sid/passport-REU "Réunion"
* $uri#http://hl7.org/fhir/sid/passport-BLM "Svatý Bartoloměj"
* $uri#http://hl7.org/fhir/sid/passport-SHN "Svatá Helena"
* $uri#http://hl7.org/fhir/sid/passport-KNA "Svatý Kryštof a Nevis"
* $uri#http://hl7.org/fhir/sid/passport-LCA "Svatá Lucie"
* $uri#http://hl7.org/fhir/sid/passport-MAF "Svatý Martin (FR)"
* $uri#http://hl7.org/fhir/sid/passport-SPM "Saint Pierre a Miquelon"
* $uri#http://hl7.org/fhir/sid/passport-VCT "Svatý Vincenc a Grenadiny"
* $uri#http://hl7.org/fhir/sid/passport-WSM "Samoa"
* $uri#http://hl7.org/fhir/sid/passport-SMR "San Marino"
* $uri#http://hl7.org/fhir/sid/passport-STP "Svatý Tomáš a Princův ostrov"
* $uri#http://hl7.org/fhir/sid/passport-SAU "Saúdská Arábie"
* $uri#http://hl7.org/fhir/sid/passport-SEN "Senegal"
* $uri#http://hl7.org/fhir/sid/passport-SRB "Srbsko"
* $uri#http://hl7.org/fhir/sid/passport-SYC "Seychely"
* $uri#http://hl7.org/fhir/sid/passport-SLE "Sierra Leone"
* $uri#http://hl7.org/fhir/sid/passport-SGP "Singapur"
* $uri#http://hl7.org/fhir/sid/passport-SXM "Svatý Martin (NL)"
* $uri#http://hl7.org/fhir/sid/passport-SVK "Slovensko"
* $uri#http://hl7.org/fhir/sid/passport-SVN "Slovinsko"
* $uri#http://hl7.org/fhir/sid/passport-SLB "Šalomounovy ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-SOM "Somálsko"
* $uri#http://hl7.org/fhir/sid/passport-ZAF "Jižní Afrika"
* $uri#http://hl7.org/fhir/sid/passport-SGS "Jižní Georgie a Jižní Sandwichovy ostrovy"
* $uri#http://hl7.org/fhir/sid/passport-SSD "Jižní Súdán"
* $uri#http://hl7.org/fhir/sid/passport-ESP "Španělsko"
* $uri#http://hl7.org/fhir/sid/passport-LKA "Šrí Lanka"
* $uri#http://hl7.org/fhir/sid/passport-SDN "Súdán"
* $uri#http://hl7.org/fhir/sid/passport-SUR "Surinam"
* $uri#http://hl7.org/fhir/sid/passport-SJM "Špicberky a Jan Mayen"
* $uri#http://hl7.org/fhir/sid/passport-SWE "Švédsko"
* $uri#http://hl7.org/fhir/sid/passport-CHE "Švýcarsko"
* $uri#http://hl7.org/fhir/sid/passport-SYR "Sýrie"
* $uri#http://hl7.org/fhir/sid/passport-TWN "Sýrie"
* $uri#http://hl7.org/fhir/sid/passport-TJK "Tádžikistán"
* $uri#http://hl7.org/fhir/sid/passport-TZA "Tádžikistán"
* $uri#http://hl7.org/fhir/sid/passport-THA "Thajsko"
* $uri#http://hl7.org/fhir/sid/passport-TLS "Východní Timor"
* $uri#http://hl7.org/fhir/sid/passport-TGO "Togo"
* $uri#http://hl7.org/fhir/sid/passport-TKL "Tokelau"
* $uri#http://hl7.org/fhir/sid/passport-TON "Tonga"
* $uri#http://hl7.org/fhir/sid/passport-TTO "Trinidad a Tobago"
* $uri#http://hl7.org/fhir/sid/passport-TUN "Tunisko"
* $uri#http://hl7.org/fhir/sid/passport-TKM "Turkmenistán"
* $uri#http://hl7.org/fhir/sid/passport-TCA "Turks a Caicos"
* $uri#http://hl7.org/fhir/sid/passport-TUV "Tuvalu"
* $uri#http://hl7.org/fhir/sid/passport-TUR "Turecko"
* $uri#http://hl7.org/fhir/sid/passport-UGA "Uganda"
* $uri#http://hl7.org/fhir/sid/passport-UKR "Ukrajina"
* $uri#http://hl7.org/fhir/sid/passport-ARE "Spojené arabské emiráty"
* $uri#http://hl7.org/fhir/sid/passport-GBR "Velká Británie"
* $uri#http://hl7.org/fhir/sid/passport-UMI "Menší odlehlé ostrovy USA"
* $uri#http://hl7.org/fhir/sid/passport-USA "Spojené státy"
* $uri#http://hl7.org/fhir/sid/passport-URY "Uruguay"
* $uri#http://hl7.org/fhir/sid/passport-UZB "Uzbekistán"
* $uri#http://hl7.org/fhir/sid/passport-VUT "Vanuatu"
* $uri#http://hl7.org/fhir/sid/passport-VEN "Venezuela"
* $uri#http://hl7.org/fhir/sid/passport-VNM "Vietnam"
* $uri#http://hl7.org/fhir/sid/passport-VGB "Vietnam"
* $uri#http://hl7.org/fhir/sid/passport-VIR "Vietnam"
* $uri#http://hl7.org/fhir/sid/passport-WLF "Wallis a Futuna"
* $uri#http://hl7.org/fhir/sid/passport-ESH "Západní Sahara"
* $uri#http://hl7.org/fhir/sid/passport-YEM "Jemen"
* $uri#http://hl7.org/fhir/sid/passport-ZMB "Zambie"
* $uri#http://hl7.org/fhir/sid/passport-ZWE "Zimbabwe"
* $uri#http://hl7.org/fhir/sid/passport-ALA "Alandy"